package com.lagradost.quicknovel.providers

import com.lagradost.quicknovel.*
import org.jsoup.Jsoup
import com.lagradost.quicknovel.MainActivity.Companion.app

class ReadfromnetProvider : MainAPI() {
    override val name = "ReadFrom.Net"
    override val mainUrl = "https://readfrom.net"
    override val hasMainPage = true

    override val iconId = R.drawable.icon_readfromnet

    override val iconBackgroundId = R.color.wuxiaWorldOnlineColor

    override val tags = listOf(
        Pair("All", "allbooks"),
        Pair("Romance", "romance"),
        Pair("Fiction", "fiction"),
        Pair("Fantasy", "fantasy"),
        Pair("Young Adult", "young-adult"),
        Pair("Contemporary", "contemporary"),
        Pair("Mystery & Thrillers", "mystery-thrillers"),
        Pair("Science Fiction & Fantasy", "science-fiction-fantasy"),
        Pair("Paranormal", "paranormal"),
        Pair("Historical Fiction", "historical-fiction"),
        Pair("Mystery", "mystery"),
        Pair("Science Fiction", "science-fiction"),
        Pair("Literature & Fiction", "literature-fiction"),
        Pair("Thriller", "thriller"),
        Pair("Horror", "horror"),
        Pair("Suspense", "suspense"),
        Pair("Nonfiction", "non-fiction"),
        Pair("Children's Books", "children-s-books"),
        Pair("Historical", "historical"),
        Pair("History", "history"),
        Pair("Crime", "crime"),
        Pair("Ebooks", "ebooks"),
        Pair("Children's", "children-s"),
        Pair("Chick Lit", "chick-lit"),
        Pair("Short Stories", "short-stories"),
        Pair("Nonfiction", "nonfiction"),
        Pair("Humor", "humor"),
        Pair("Poetry", "poetry"),
        Pair("Erotica", "erotica"),
        Pair("Humor and Comedy", "humor-and-comedy"),
        Pair("Classics", "classics"),
        Pair("Gay and Lesbian", "gay-and-lesbian"),
        Pair("Biography", "biography"),
        Pair("Childrens", "childrens"),
        Pair("Memoir", "memoir"),
        Pair("Adult Fiction", "adult-fiction"),
        Pair("Biographies & Memoirs", "biographies-memoirs"),
        Pair("New Adult", "new-adult"),
        Pair("Gay & Lesbian", "gay-lesbian"),
        Pair("Womens Fiction", "womens-fiction"),
        Pair("Science", "science"),
        Pair("Historical Romance", "historical-romance"),
        Pair("Cultural", "cultural"),
        Pair("Vampires", "vampires"),
        Pair("Urban Fantasy", "urban-fantasy"),
        Pair("Sports", "sports"),
        Pair("Religion & Spirituality", "religion-spirituality"),
        Pair("Paranormal Romance", "paranormal-romance"),
        Pair("Dystopia", "dystopia"),
        Pair("Politics", "politics"),
        Pair("Travel", "travel"),
        Pair("Christian Fiction", "christian-fiction"),
        Pair("Philosophy", "philosophy"),
        Pair("Religion", "religion"),
        Pair("Autobiography", "autobiography"),
        Pair("M M Romance", "m-m-romance"),
        Pair("Cozy Mystery", "cozy-mystery"),
        Pair("Adventure", "adventure"),
        Pair("Comics & Graphic Novels", "comics-graphic-novels"),
        Pair("Business", "business"),
        Pair("Polyamorous", "polyamorous"),
        Pair("Reverse Harem", "reverse-harem"),
        Pair("War", "war"),
        Pair("Writing", "writing"),
        Pair("Self Help", "self-help"),
        Pair("Music", "music"),
        Pair("Art", "art"),
        Pair("Language", "language"),
        Pair("Westerns", "westerns"),
        Pair("BDSM", "bdsm"),
        Pair("Middle Grade", "middle-grade"),
        Pair("Western", "western"),
        Pair("Psychology", "psychology"),
        Pair("Comics", "comics"),
        Pair("Romantic Suspense", "romantic-suspense"),
        Pair("Shapeshifters", "shapeshifters"),
        Pair("Spirituality", "spirituality"),
        Pair("Picture Books", "picture-books"),
        Pair("Holiday", "holiday"),
        Pair("Animals", "animals"),
        Pair("Anthologies", "anthologies"),
        Pair("Menage", "menage"),
        Pair("Zombies", "zombies"),
        Pair("Realistic Fiction", "realistic-fiction"),
        Pair("Reference", "reference"),
        Pair("LGBT", "lgbt"),
        Pair("Lesbian Fiction", "lesbian-fiction"),
        Pair("Food and Drink", "food-and-drink"),
        Pair("Mystery Thriller", "mystery-thriller"),
        Pair("Outdoors & Nature", "outdoors-nature"),
        Pair("Christmas", "christmas"),
        Pair("Sequential Art", "sequential-art"),
        Pair("Novels", "novels"),
        Pair("Military Fiction", "military-fiction"),
        Pair("Graphic Novels", "graphic-novels"),
        Pair("Post Apocalyptic", "post-apocalyptic"),
        Pair("Apocalyptic", "apocalyptic"),
        Pair("True Crime", "true-crime"),
        Pair("Interracial Romance", "interracial-romance"),
        Pair("Cookbooks", "cookbooks"),
        Pair("Plays", "plays"),
        Pair("Dark", "dark"),
        Pair("Literature", "literature"),
        Pair("GLBT", "glbt"),
        Pair("Cooking, Food & Wine", "cooking-food-wine"),
        Pair("Economics", "economics"),
        Pair("Magic", "magic"),
        Pair("Entertainment", "entertainment"),
        Pair("Health", "health"),
        Pair("Novella", "novella"),
        Pair("Academic", "academic"),
        Pair("Drama", "drama"),
        Pair("Sociology", "sociology"),
        Pair("Lesbian Romance", "lesbian-romance"),
        Pair("Arts & Photography", "arts-photography"),
        Pair("European Literature", "european-literature"),
        Pair("Literary Fiction", "literary-fiction"),
        Pair("African American", "african-american"),
        Pair("Women & Gender Studies", "women-gender-studies"),
        Pair("Adult", "adult"),
        Pair("Steampunk", "steampunk"),
        Pair("Time Travel", "time-travel"),
        Pair("World War II", "world-war-ii"),
        Pair("Erotic", "erotic"),
        Pair("Light Novel", "light-novel"),
        Pair("Aliens", "aliens"),
        Pair("Urban", "urban"),
        Pair("Women's Fiction", "women-s-fiction"),
        Pair("Theatre", "theatre"),
        Pair("Military History", "military-history"),
        Pair("Health, Mind & Body", "health-mind-body"),
        Pair("Manga", "manga"),
        Pair("Category Romance", "category-romance"),
        Pair("Juvenile", "juvenile"),
        Pair("Feminism", "feminism"),
        Pair("Canada", "canada"),
        Pair("Lesbian", "lesbian"),
        Pair("Essays", "essays"),
        Pair("Science Fiction Romance", "science-fiction-romance"),
        Pair("Social Sciences", "social-sciences"),
        Pair("Action", "action"),
        Pair("Media Tie In", "media-tie-in"),
        Pair("Paranormal Fiction", "paranormal-fiction"),
        Pair("Business & Investing", "business-investing"),
        Pair("Environment", "environment"),
        Pair("Regency Romance", "regency-romance"),
        Pair("Action Adventure", "action-adventure"),
        Pair("Magical Realism", "magical-realism"),
        Pair("Audiobook", "audiobook"),
        Pair("Space", "space"),
        Pair("Regency", "regency"),
        Pair("Parenting & Families", "parenting-families"),
        Pair("Criticism", "criticism"),
        Pair("Africa", "africa"),
        Pair("Education", "education"),
        Pair("Home & Garden", "home-garden"),
        Pair("Alternate History", "alternate-history"),
        Pair("Space Opera", "space-opera"),
        Pair("Mythology", "mythology"),
        Pair("Dragons", "dragons"),
        Pair("Finance", "finance"),
        Pair("Traditional Regency", "traditional-regency"),
        Pair("Dark Romance", "dark-romance"),
        Pair("Cooking", "cooking"),
        Pair("Australia", "australia"),
        Pair("Culture", "culture"),
        Pair("Law", "law"),
        Pair("Spy Thriller", "spy-thriller"),
        Pair("Dark Fantasy", "dark-fantasy"),
        Pair("Epic Fantasy", "epic-fantasy"),
        Pair("Inspirational", "inspirational"),
        Pair("Theology", "theology"),
        Pair("Food", "food"),
        Pair("Mathematics", "mathematics"),
        Pair("Textbooks", "textbooks"),
        Pair("Literary Criticism", "literary-criticism"),
        Pair("Crafts", "crafts"),
        Pair("Christianity", "christianity"),
        Pair("Games", "games"),
        Pair("Nature", "nature"),
        Pair("Harem", "harem"),
        Pair("North American Hi...", "north-american-history"),
        Pair("Love Inspired", "love-inspired"),
        Pair("Film", "film"),
        Pair("African American Romance", "african-american-romance"),
        Pair("Humanities", "humanities"),
        Pair("School", "school"),
        Pair("Role Playing Games", "role-playing-games"),
        Pair("Young Adult Romance", "young-adult-romance"),
        Pair("Professional & Technical", "professional-technical"),
        Pair("Espionage", "espionage"),
        Pair("Dystopian", "dystopian"),
        Pair("Urban Fantasy Romance", "urban-fantasy-romance"),
        Pair("Japan", "japan"),
        Pair("Photography", "photography"),
        Pair("Parenting", "parenting"),
        Pair("Fairy Tales", "fairy-tales"),
        Pair("Horses", "horses"),
        Pair("Clean Romance", "clean-romance"),
        Pair("France", "france"),
        Pair("Gothic", "gothic"),
        Pair("Abuse", "abuse"),
        Pair("Journalism", "journalism"),
        Pair("Biography Memoir", "biography-memoir"),
        Pair("BDSM Romance", "bdsm-romance"),
        Pair("Superheroes", "superheroes"),
        Pair("Gardening", "gardening"),
        Pair("New Adult, Historical Fiction", "new-adult-historical-fiction"),
        Pair("Couture", "couture"),
        Pair("Baseball", "baseball"),
        Pair("Russia", "russia"),
        Pair("Romantic Comedy", "romantic-comedy"),
        Pair("Thrillers", "thrillers"),
        Pair("Fantasy Romance", "fantasy-romance"),
        Pair("Speculative Fiction", "speculative-fiction"),
        Pair("Books About Books", "books-about-books"),
        Pair("Western Romance", "western-romance"),
        Pair("Computer Science", "computer-science"),
        Pair("Fairies", "fairies"),
        Pair("Crime Fiction", "crime-fiction"),
        Pair("Young Adult, New Adult", "young-adult-new-adult"),
        Pair("Historical Romantic Western", "historical-romantic-western"),
        Pair("China", "china"),
        Pair("Chapter Books", "chapter-books"),
        Pair("Holocaust", "holocaust"),
        Pair("Crafts & Hobbies", "crafts-hobbies"),
        Pair("Survival", "survival"),
        Pair("Fashion", "fashion"),
        Pair("Historical Mystery", "historical-mystery"),
        Pair("Ireland", "ireland"),
        Pair("Family", "family"),
        Pair("Medieval", "medieval"),
        Pair("American", "american"),
        Pair("Theater", "theater"),
        Pair("Motorcycle", "motorcycle"),
        Pair("Civil War", "civil-war"),
        Pair("World War I", "world-war-i"),
        Pair("Litrpg", "litrpg"),
        Pair("Leadership", "leadership"),
        Pair("Military", "military"),
        Pair("Cozy Mysteries", "cozy-mysteries"),
        Pair("Action Romance", "action-romance"),
        Pair("Military Science Fiction", "military-science-fiction"),
        Pair("Folklore", "folklore"),
        Pair("Detective & Western", "detective-western"),
        Pair("Architecture", "architecture"),
        Pair("American History", "american-history"),
        Pair("Gay", "gay"),
        Pair("British Literature", "british-literature"),
        Pair("Technology", "technology"),
        Pair("Retellings", "retellings"),
        Pair("Design", "design"),
        Pair("Mental Health", "mental-health"),
        Pair("Witches", "witches"),
        Pair("Post Apocalypse", "post-apocalypse"),
        Pair("New Adult Romance", "new-adult-romance"),
        Pair("Football", "football"),
        Pair("Alternative History", "alternative-history"),
        Pair("Werewolves", "werewolves"),
        Pair("Transport", "transport"),
        Pair("Animal Fiction", "animal-fiction"),
        Pair("Young Adult, New Adult, Adult", "young-adult-new-adult-adult"),
        Pair("Queer", "queer"),
        Pair("Computers & Internet", "computers-internet"),
        Pair("Terrorism", "terrorism"),
        Pair("Teaching", "teaching"),
        Pair("New York", "new-york"),
        Pair("Cats", "cats"),
        Pair("Anthropology", "anthropology"),
        Pair("Christian Romance", "christian-romance"),
        Pair("Dogs", "dogs"),
        Pair("Cyberpunk", "cyberpunk"),
        Pair("Medical", "medical"),
        Pair("Lds", "lds"),
        Pair("Fae", "fae"),
        Pair("Emergency Services", "emergency-services"),
        Pair("Rock Stars", "rock-stars"),
        Pair("Paranormal & Fantasy", "paranormal-fantasy"),
        Pair("Occult", "occult"),
        Pair("Weird Fiction", "weird-fiction"),
        Pair("Dark Erotica", "dark-erotica"),
        Pair("Culinary", "culinary"),
        Pair("Medieval Romance", "medieval-romance"),
        Pair("Supernatural", "supernatural"),
        Pair("Pulp", "pulp"),
        Pair("Intense Emotional Fiction", "intense-emotional-fiction"),
        Pair("Noir", "noir"),
        Pair("College", "college"),
        Pair("BDSM and D/s", "bdsm-and-d-s"),
        Pair("Angels", "angels"),
        Pair("Young Adult Fiction", "young-adult-fiction"),
        Pair("Race", "race"),
        Pair("Buddhism", "buddhism"),
        Pair("Satire", "satire"),
        Pair("Physics", "physics"),
        Pair("Love Inspired Suspense", "love-inspired-suspense"),
        Pair("Disambiguation Profile", "disambiguation-profile"),
        Pair("Personal Finance", "personal-finance"),
        Pair("M F Romance", "m-f-romance"),
        Pair("Italy", "italy"),
        Pair("Ghost Stories", "ghost-stories"),
        Pair("YA Mystery/suspense", "ya-mystery-suspense"),
        Pair("Romance/suspense", "romance-suspense"),
        Pair("Psychological Thriller", "psychological-thriller"),
        Pair("Novelizations", "novelizations"),
        Pair("Splatter Punk", "splatter-punk"),
        Pair("Relationships", "relationships"),
        Pair("Bizarro Fiction", "bizarro-fiction"),
        Pair("Mystery and Thrillers", "mystery-and-thrillers"),
        Pair("Ghosts", "ghosts"),
        Pair("Engineering", "engineering"),
        Pair("Coming Of Age", "coming-of-age"),
        Pair("Church", "church"),
        Pair("Archaeology", "archaeology"),
        Pair("Programming", "programming"),
        Pair("Linguistics", "linguistics"),
        Pair("German Literature", "german-literature"),
        Pair("Disambiguation", "disambiguation"),
        Pair("Sexuality", "sexuality"),
        Pair("Post Apocalyptic Fiction", "post-apocalyptic-fiction"),
        Pair("Lesbian Mystery", "lesbian-mystery"),
        Pair("Social Issues", "social-issues"),
        Pair("Gay Romance", "gay-romance"),
        Pair("Biology", "biology"),
        Pair("Research", "research"),
        Pair("Mystery & Thrillers, Particularl", "mystery-thrillers-particularl"),
        Pair("Pirates", "pirates"),
        Pair("Knitting", "knitting"),
        Pair("Islam", "islam"),
        Pair("Female Authors", "female-authors"),
        Pair("Medicine", "medicine"),
        Pair("Biblical Fiction", "biblical-fiction"),
        Pair("Supernatural Thriller", "supernatural-thriller"),
        Pair("Halloween", "halloween"),
        Pair("Gothic Romance", "gothic-romance"),
        Pair("Asian Literature", "asian-literature"),
        Pair("Southern Gothic", "southern-gothic"),
        Pair("Shifter Romance", "shifter-romance"),
        Pair("Quilting", "quilting"),
        Pair("Political Science", "political-science"),
        Pair("The United States Of America", "the-united-states-of-america"),
        Pair("Teen", "teen"),
        Pair("Sci Fi", "sci-fi"),
        Pair("Nurses", "nurses"),
        Pair("Mysteries", "mysteries"),
        Pair("BDSM Erotica", "bdsm-erotica"),
        Pair("YA Fantasy", "ya-fantasy"),
        Pair("Unfinished", "unfinished"),
        Pair("Romance & Mainstream Women's Fic", "romance-mainstream-women-s-fic"),
        Pair("Movies", "movies"),
        Pair("Womens", "womens"),
        Pair("Own", "own"),
        Pair("Nursing", "nursing"),
        Pair("Modern & Contemporary Fiction", "modern-contemporary-fiction"),
        Pair("Historical Fantasy", "historical-fantasy"),
        Pair("Harlequin Presents", "harlequin-presents"),
        Pair("Comedy", "comedy"),
        Pair("Scotland", "scotland"),
        Pair("Omegaverse", "omegaverse"),
        Pair("Love Stories", "love-stories"),
        Pair("Gaming", "gaming"),
        Pair("Sports and Games", "sports-and-games"),
        Pair("M M F", "m-m-f"),
        Pair("Foods", "foods"),
        Pair("Birds", "birds"),
        Pair("Southern Fiction", "southern-fiction"),
        Pair("Pop Culture", "pop-culture"),
        Pair("Murder Mystery", "murder-mystery"),
        Pair("Humor & Comedy", "humor-comedy"),
        Pair("Fitness", "fitness"),
        Pair("Roman", "roman"),
        Pair("Northern Africa", "northern-africa"),
        Pair("Management", "management"),
        Pair("High School", "high-school"),
        Pair("Collections", "collections"),
        Pair("Transgender", "transgender"),
        Pair("Jewish", "jewish"),
        Pair("Interracial", "interracial"),
        Pair("Essay", "essay"),
        Pair("Boxing", "boxing"),
        Pair("Art History", "art-history"),
        Pair("Young Adult Fantasy", "young-adult-fantasy"),
        Pair("Thrillers & Suspense", "thrillers-suspense"),
        Pair("M/m", "m-m"),
        Pair("Judaism", "judaism"),
        Pair("Historical Fiction, Horror", "historical-fiction-horror"),
        Pair("High Fantasy", "high-fantasy"),
        Pair("Fan Fiction", "fan-fiction"),
        Pair("Family Saga", "family-saga"),
        Pair("Storytime", "storytime"),
        Pair("Reverse Harem Fantasy Romance", "reverse-harem-fantasy-romance"),
        Pair("Mystery/suspense", "mystery-suspense"),
        Pair("Israel", "israel"),
        Pair("Humorous Contemporary Romance", "humorous-contemporary-romance"),
        Pair("Hard Boiled", "hard-boiled"),
        Pair("Disability", "disability"),
        Pair("Psychological Thrillers", "psychological-thrillers"),
        Pair("Library Science", "library-science"),
        Pair("Lds Fiction", "lds-fiction"),
        Pair("Irish Literature", "irish-literature"),
        Pair("Cycling", "cycling"),
        Pair("Computers", "computers"),
        Pair("Catholic", "catholic"),
        Pair("Aviation", "aviation"),
        Pair("Atheism", "atheism"),
        Pair("Translation", "translation"),
        Pair("Screenplays", "screenplays"),
        Pair("Pseudoscience", "pseudoscience"),
        Pair("Paranormal and Fantasy", "paranormal-and-fantasy"),
        Pair("Monsters", "monsters"),
        Pair("Horror & Suspense", "horror-suspense"),
        Pair("Dinosaurs", "dinosaurs"),
        Pair("Surrealism", "surrealism"),
        Pair("Marriage", "marriage"),
        Pair("Astronomy", "astronomy"),
        Pair("Historical Paranormal Romance", "historical-paranormal-romance"),
        Pair("Dark Fiction", "dark-fiction"),
        Pair("Theory", "theory"),
        Pair("Romantic Erotica", "romantic-erotica"),
        Pair("Naval History", "naval-history"),
        Pair("Gender", "gender"),
        Pair("Fantasy/urban Fiction", "fantasy-urban-fiction"),
        Pair("40k", "40k"),
        Pair("Social Science", "social-science"),
        Pair("Reproductive Justice", "reproductive-justice"),
        Pair("Pulp Fiction", "pulp-fiction"),
        Pair("Narration", "narration"),
        Pair("Military Romance", "military-romance"),
        Pair("Literary", "literary"),
        Pair("Hockey", "hockey"),
        Pair("Esoterica", "esoterica"),
        Pair("Demons", "demons"),
        Pair("Cities", "cities"),
        Pair("Witchcraft", "witchcraft"),
        Pair("Technical", "technical"),
        Pair("Mythology & Fantasy", "mythology-fantasy"),
        Pair("Catholicism", "catholicism"),
        Pair("African American Literature", "african-american-literature"),
        Pair("Teen Fiction", "teen-fiction"),
        Pair("Suspense Romance", "suspense-romance"),
        Pair("Southern", "southern"),
        Pair("Romantice Suspense", "romantice-suspense"),
        Pair("Personal Development", "personal-development"),
        Pair("Paranormal Mystery", "paranormal-mystery"),
        Pair("Fantasy, Paranormal", "fantasy-paranormal"),
        Pair("Cozy", "cozy"),
        Pair("Counselling", "counselling"),
        Pair("Billionaire Romance", "billionaire-romance"),
        Pair("Alpha Male Romance", "alpha-male-romance"),
        Pair("Adoption", "adoption"),
        Pair("Women's Studies", "women-s-studies"),
        Pair("Time Travel Romance", "time-travel-romance"),
        Pair("Sports Romance", "sports-romance"),
        Pair("Speculative", "speculative"),
        Pair("Mountaineering", "mountaineering"),
        Pair("Mafia", "mafia"),
        Pair("Astrology", "astrology"),
        Pair("Paranromal Romance", "paranromal-romance"),
        Pair("Litrpg/gamelit", "litrpg-gamelit"),
        Pair("Lesbian Erotica", "lesbian-erotica"),
        Pair("Humour", "humour"),
        Pair("English History", "english-history"),
        Pair("Death", "death"),
        Pair("Books For Young Readers", "books-for-young-readers"),
        Pair("Scotland Set Historical Romance,", "scotland-set-historical-romance"),
        Pair("Mystery/psychological Thriller", "mystery-psychological-thriller"),
        Pair("Mature Young Adult/ New Adult", "mature-young-adult-new-adult"),
        Pair("Mature YA", "mature-ya"),
        Pair("Jazz", "jazz"),
        Pair("Greece", "greece"),
        Pair("Geology", "geology"),
        Pair("Folk Tales", "folk-tales"),
        Pair("Contemp. Romance", "contemp-romance"),
        Pair("Comic Books", "comic-books"),
        Pair("Victorian", "victorian"),
        Pair("Tudor Period", "tudor-period"),
        Pair("Southern Africa", "southern-africa"),
        Pair("Kids", "kids"),
        Pair("Family Law", "family-law"),
        Pair("Exploration", "exploration"),
        Pair("Egypt", "egypt"),
        Pair("Children's Fiction", "children-s-fiction"),
        Pair("Asia", "asia"),
        Pair("American Civil War", "american-civil-war"),
        Pair("Absurdism", "absurdism"),
        Pair("Urban Planning", "urban-planning"),
        Pair("Splatterpunk", "splatterpunk"),
        Pair("Several", "several"),
        Pair("International Relations", "international-relations"),
        Pair("Heroic Fantasy", "heroic-fantasy"),
        Pair("Dark Romance, Dark Romantic Susp", "dark-romance-dark-romantic-susp"),
        Pair("Communication", "communication"),
        Pair("Civil Rights", "civil-rights"),
        Pair("Christian Living", "christian-living"),
        Pair("Adventures", "adventures"),
        Pair("Wuxia", "wuxia"),
        Pair("Psychological Romance", "psychological-romance"),
        Pair("How To", "how-to"),
        Pair("Contemporary & Romantic Comedy", "contemporary-romantic-comedy"),
        Pair("Writing Craft", "writing-craft"),
        Pair("Suspense, Paranormal Romance", "suspense-paranormal-romance"),
        Pair("South Africa", "south-africa"),
        Pair("Romantic", "romantic"),
        Pair("Musicology", "musicology"),
        Pair("Military Romantic Suspense", "military-romantic-suspense"),
        Pair("Love", "love"),
        Pair("Japanese Literature", "japanese-literature"),
        Pair("Historical, Contemporary Romanc", "historical-contemporary-romanc"),
        Pair("Gonzo Journalism", "gonzo-journalism"),
        Pair("Geography", "geography"),
        Pair("Fantasy,sword and Sorcery", "fantasy-sword-and-sorcery"),
        Pair("Combat", "combat"),
        Pair("Alcohol", "alcohol"),
        Pair("Action/suspense Romance", "action-suspense-romance"),
        Pair("Warfare", "warfare"),
        Pair("Prayer", "prayer"),
        Pair("Police", "police"),
        Pair("Paranormal Suspence", "paranormal-suspence"),
        Pair("Martial Arts", "martial-arts"),
        Pair("Italian Literature", "italian-literature"),
        Pair("Humor and Satire", "humor-and-satire"),
        Pair("History and Military History", "history-and-military-history"),
        Pair("Historical Fantasy Romance", "historical-fantasy-romance"),
        Pair("Ethics", "ethics"),
        Pair("Erotic Science Fiction & Fantasy", "erotic-science-fiction-fantasy"),
        Pair("Epic Fantasy Romance", "epic-fantasy-romance"),
        Pair("Contemporary Erotic", "contemporary-erotic"),
        Pair("Buffy The Vampire Slayer", "buffy-the-vampire-slayer"),
        Pair("Adult Paranormal Romance", "adult-paranormal-romance"),
        Pair("Wildlife", "wildlife"),
        Pair("Technical Trades", "technical-trades"),
        Pair("Steamy Romance", "steamy-romance"),
        Pair("Spirituality & Philosophy", "spirituality-philosophy"),
        Pair("Spanish Literature", "spanish-literature"),
        Pair("Songs, Poetry & Arts", "songs-poetry-arts"),
        Pair("Racing", "racing"),
        Pair("Pornography", "pornography"),
        Pair("Pakistan", "pakistan"),
        Pair("Mental Illness", "mental-illness"),
        Pair("Iran", "iran"),
        Pair("Historical Western", "historical-western"),
        Pair("Historical Christian Romance", "historical-christian-romance"),
        Pair("Health Care", "health-care"),
        Pair("Graphic Novels Comics", "graphic-novels-comics"),
        Pair("Gamebooks", "gamebooks"),
        Pair("Fighters", "fighters"),
        Pair("Entrepreneurship", "entrepreneurship"),
        Pair("Domestic Fiction", "domestic-fiction"),
        Pair("Dance", "dance"),
        Pair("Contemporary Christian Romance", "contemporary-christian-romance"),
        Pair("Church History", "church-history"),
        Pair("Chess", "chess"),
        Pair("Bizarro", "bizarro"),
        Pair("Arthurian", "arthurian"),
        Pair("American Revolution", "american-revolution"),
        Pair("Urban Magic", "urban-magic"),
        Pair("Theatre & Film", "theatre-film"),
        Pair("Supernatural/horror", "supernatural-horror"),
        Pair("Ornithology", "ornithology"),
        Pair("New Adult/ Young Adult", "new-adult-young-adult"),
        Pair("M F M", "m-f-m"),
        Pair("Lovecraftian", "lovecraftian"),
        Pair("LGBTQ+", "lgbtq"),
        Pair("History Of Ideas", "history-of-ideas"),
        Pair("Historicals, Mystery", "historicals-mystery"),
        Pair("Highlands and Islands", "highlands-and-islands"),
        Pair("Highland History", "highland-history"),
        Pair("Guidebook", "guidebook"),
        Pair("Georgian, Regency, Medieval, Sco", "georgian-regency-medieval-sco"),
        Pair("Film Studies", "film-studies"),
        Pair("Epic", "epic"),
        Pair("Currency", "currency"),
        Pair("Book Club", "book-club"),
        Pair("YA", "ya"),
        Pair("Supernatural Thrillers", "supernatural-thrillers"),
        Pair("Scifi", "scifi"),
        Pair("Sci Fi Romance", "sci-fi-romance"),
        Pair("Legal Thriller", "legal-thriller"),
        Pair("Historical Menage", "historical-menage"),
        Pair("Czech Literature", "czech-literature"),
        Pair("Calvinism", "calvinism"),
        Pair("Bisexual", "bisexual"),
        Pair("Zombie", "zombie"),
        Pair("Young Adult Books", "young-adult-books"),
        Pair("Time Slip", "time-slip"),
        Pair("Sustainability", "sustainability"),
        Pair("Spain", "spain"),
        Pair("Software", "software"),
        Pair("Social Work", "social-work"),
        Pair("Race Studies", "race-studies"),
        Pair("Paranormal, Contemporary", "paranormal-contemporary"),
        Pair("Natural History", "natural-history"),
        Pair("Money", "money"),
        Pair("Mermaids", "mermaids"),
        Pair("Jewish Religion", "jewish-religion"),
        Pair("Germany", "germany"),
        Pair("Game Novelization", "game-novelization"),
        Pair("Fantasy / Crime / Mystery", "fantasy-crime-mystery"),
        Pair("Erotica/ Dark Romance", "erotica-dark-romance"),
        Pair("Erotic Suspense", "erotic-suspense"),
        Pair("Dystopian Fiction", "dystopian-fiction"),
        Pair("Crochet", "crochet"),
        Pair("Contemporary Fiction", "contemporary-fiction"),
        Pair("Contemporary Erotica", "contemporary-erotica"),
        Pair("Confessional Erotica", "confessional-erotica"),
        Pair("Class", "class"),
        Pair("Celtic Fantasy/historical", "celtic-fantasy-historical"),
        Pair("Amish Fiction", "amish-fiction"),
        Pair("Adventure Travel", "adventure-travel"),
        Pair("Zen", "zen"),
        Pair("War Novels", "war-novels"),
        Pair("Sweet Romance", "sweet-romance"),
        Pair("Suspenseful Romance", "suspenseful-romance"),
        Pair("Superhero", "superhero"),
        Pair("Screenplays & Plays", "screenplays-plays"),
        Pair("Psychoanalysis", "psychoanalysis"),
        Pair("Plays & Screenplays", "plays-screenplays"),
        Pair("Paranormal Erotic Romance", "paranormal-erotic-romance"),
        Pair("New Adult, Time Travel Romance", "new-adult-time-travel-romance"),
        Pair("Motoring", "motoring"),
        Pair("Military Thriller", "military-thriller"),
        Pair("Medieval Historical Romance", "medieval-historical-romance"),
        Pair("Historical Western Romance", "historical-western-romance"),
        Pair("Grad School", "grad-school"),
        Pair("Gothic Romance, Urban Fantasy", "gothic-romance-urban-fantasy"),
        Pair("Experimental", "experimental"),
        Pair("Ecology", "ecology"),
        Pair("Dauntless Romance", "dauntless-romance"),
        Pair("Colouring Books", "colouring-books"),
        Pair("Chemistry", "chemistry"),
        Pair("Basketball", "basketball"),
        Pair("Adult, New Adult", "adult-new-adult"),
        Pair("Action and Adventure", "action-and-adventure"),
        Pair("Young Adult and Adult Thrillers", "young-adult-and-adult-thrillers"),
        Pair("Trivia", "trivia"),
        Pair("Sewing", "sewing"),
        Pair("Rpg", "rpg"),
        Pair("Romance, Erotica, BDSM", "romance-erotica-bdsm"),
        Pair("Railways", "railways"),
        Pair("Mm", "mm"),
        Pair("Mature Young Adult", "mature-young-adult"),
        Pair("M M M", "m-m-m"),
        Pair("Fiction & Literature", "fiction-literature"),
        Pair("Fairytales", "fairytales"),
        Pair("Erotic Historical Romance", "erotic-historical-romance"),
        Pair("D/s Erotica", "d-s-erotica"),
        Pair("Cultural Studies", "cultural-studies"),
        Pair("Cinema", "cinema"),
        Pair("BDSM Erotica. Erotic Romance", "bdsm-erotica-erotic-romance"),
        Pair("Young Adult/tweens", "young-adult-tweens"),
        Pair("World History", "world-history"),
        Pair("Vampires, Shifters and Magic!", "vampires-shifters-and-magic"),
        Pair("Tarot", "tarot"),
        Pair("Sword and Sorcery", "sword-and-sorcery"),
        Pair("Social", "social"),
        Pair("Sci Fi Romance (sfr)", "sci-fi-romance-sfr"),
        Pair("Sci/fi & Fantasy, New Adult", "sci-fi-fantasy-new-adult"),
        Pair("Russian Literature", "russian-literature"),
        Pair("Russian History", "russian-history"),
        Pair("Regency Set Mystery", "regency-set-mystery"),
        Pair("Read For School", "read-for-school"),
        Pair("Paranormal Romance (pnr)", "paranormal-romance-pnr"),
        Pair("Paganism", "paganism"),
        Pair("Nonfiction, Contemporary Women's", "nonfiction-contemporary-women-s"),
        Pair("New Pulp", "new-pulp"),
        Pair("Nautical", "nautical"),
        Pair("Mysticism", "mysticism"),
        Pair("Murder", "murder"),
        Pair("Modern", "modern"),
        Pair("Material Culture", "material-culture"),
        Pair("Loveswept", "loveswept"),
        Pair("Humor/cozy", "humor-cozy"),
        Pair("Historical Scottish Romance", "historical-scottish-romance"),
        Pair("Green Marketing", "green-marketing"),
        Pair("Gay Fiction", "gay-fiction"),
        Pair("Dystopian Fantasy", "dystopian-fantasy"),
        Pair("Dc Comics", "dc-comics"),
        Pair("Dark Science Fiction & Fantasy", "dark-science-fiction-fantasy"),
        Pair("Dark Historical Fiction, Mystery", "dark-historical-fiction-mystery"),
        Pair("Cyber Fantasy", "cyber-fantasy"),
        Pair("Contemporary Romance / Southern", "contemporary-romance-southern"),
        Pair("Commercial Women's Fiction", "commercial-women-s-fiction"),
        Pair("Choose Your Own Adventure", "choose-your-own-adventure"),
        Pair("Children's, Young Adult", "children-s-young-adult"),
        Pair("Beauty and The Beast", "beauty-and-the-beast"),
        Pair("Applied and Social Theatre", "applied-and-social-theatre"),
        Pair("Ancient History", "ancient-history"),
        Pair("21st Century", "21st-century"),
        Pair("20th Century", "20th-century"),
        Pair("Young Adult, Late Middle Grade", "young-adult-late-middle-grade"),
        Pair("Yaoi", "yaoi"),
        Pair("Tragicomedy", "tragicomedy"),
        Pair("Social Media", "social-media"),
        Pair("Science Fiction, Cyberpunk", "science-fiction-cyberpunk"),
        Pair("Rural", "rural"),
        Pair("Romantic Women's Fiction & Mys", "romantic-women-s-fiction-mys"),
        Pair("Romance! New Adult", "romance-new-adult"),
        Pair("Real Life Experiences", "real-life-experiences"),
        Pair("Philosophy & Spirituality", "philosophy-spirituality"),
        Pair("New Adult, Contemporary Romance", "new-adult-contemporary-romance"),
        Pair("Mystery, Thriller, Fantasy", "mystery-thriller-fantasy"),
        Pair("Movie Tie Ins", "movie-tie-ins"),
        Pair("Medievalism", "medievalism"),
        Pair("Magick", "magick"),
        Pair("Literature & Nonfiction", "literature-nonfiction"),
        Pair("LGBT Romance", "lgbt-romance"),
        Pair("Judaica", "judaica"),
        Pair("Investigation", "investigation"),
        Pair("Harlequin Romance", "harlequin-romance"),
        Pair("Harlequin Blaze", "harlequin-blaze"),
        Pair("Graphic Novel", "graphic-novel"),
        Pair("Fantasy, Paranormal, Urban", "fantasy-paranormal-urban"),
        Pair("English Literature", "english-literature"),
        Pair("Doctors", "doctors"),
        Pair("Country Noir", "country-noir"),
        Pair("Contemporary Romance/mystery", "contemporary-romance-mystery"),
        Pair("Conservation", "conservation"),
        Pair("Children With Special Needs", "children-with-special-needs"),
        Pair("Children's Picture Books", "children-s-picture-books"),
        Pair("Canadian Literature", "canadian-literature"),
        Pair("Australiana", "australiana"),
        Pair("Young Adult and New Adult", "young-adult-and-new-adult"),
        Pair("Wicca", "wicca"),
        Pair("Videogames", "videogames"),
        Pair("Veterinary Medicine", "veterinary-medicine"),
        Pair("Tv", "tv"),
        Pair("Teens, Tweens, Children, Adults", "teens-tweens-children-adults"),
        Pair("Teachers", "teachers"),
        Pair("Street Lit", "street-lit"),
        Pair("Social Movements", "social-movements"),
        Pair("Scottish Literary History", "scottish-literary-history"),
        Pair("Science Fiction Adventure", "science-fiction-adventure"),
        Pair("Sci Fi & Post Apocalyptic", "sci-fi-post-apocalyptic"),
        Pair("Romantic Thriller", "romantic-thriller"),
        Pair("Political Thriller", "political-thriller"),
        Pair("Poetry In Scots", "poetry-in-scots"),
        Pair("Performing Arts", "performing-arts"),
        Pair("Paranormal Erotica", "paranormal-erotica"),
        Pair("Paranormal, and Children's", "paranormal-and-children-s"),
        Pair("Paranormal & Mystery Romance", "paranormal-mystery-romance"),
        Pair("Naturalism", "naturalism"),
        Pair("Native American", "native-american"),
        Pair("Mythological/historical Fiction", "mythological-historical-fiction"),
        Pair("Mystery, Suspense, & Thrillers", "mystery-suspense-thrillers"),
        Pair("Mystery & Crime", "mystery-crime"),
        Pair("Mail Order Brides", "mail-order-brides"),
        Pair("Lighthearted Adventures", "lighthearted-adventures"),
        Pair("Inspirational Western Romance", "inspirational-western-romance"),
        Pair("Indian Literature", "indian-literature"),
        Pair("Gay and Lesbian, M/f", "gay-and-lesbian-m-f"),
        Pair("Futuristic", "futuristic"),
        Pair("Fostering", "fostering"),
        Pair("Firearms", "firearms"),
        Pair("Field Guides", "field-guides"),
        Pair("Fantasy, Sci Fi & Horror", "fantasy-sci-fi-horror"),
        Pair("Erotic Fiction", "erotic-fiction"),
        Pair("Diaries", "diaries"),
        Pair("Contemporary Romance and Erotica", "contemporary-romance-and-erotica"),
        Pair("African Studies", "african-studies"),
        Pair("African American Fiction", "african-american-fiction"),
        Pair("Young Adult Paranormal Romance", "young-adult-paranormal-romance"),
        Pair("Young Adult, Mainstream", "young-adult-mainstream"),
        Pair("Visual Art", "visual-art"),
        Pair("Video Games", "video-games"),
        Pair("Soft Porn", "soft-porn"),
        Pair("Science Fiction and Fantasy", "science-fiction-and-fantasy"),
        Pair("Saga", "saga"),
        Pair("Romantic Suspense & Fantasy", "romantic-suspense-fantasy"),
        Pair("Romania", "romania"),
        Pair("Romance and Erotic Romance", "romance-and-erotic-romance"),
        Pair("Romance Thriller Suspense", "romance-thriller-suspense"),
        Pair("Roleplaying Games", "roleplaying-games"),
        Pair("Preservation", "preservation"),
        Pair("Paranormal Romance & Fantasy Rom", "paranormal-romance-fantasy-rom"),
        Pair("Mythic Fantasy", "mythic-fantasy"),
        Pair("Mystery & Adventure", "mystery-adventure"),
        Pair("Museology", "museology"),
        Pair("Mm Romance", "mm-romance"),
        Pair("Military Art & Science", "military-art-science"),
        Pair("Military/war", "military-war"),
        Pair("History/alternate History Fictio", "history-alternate-history-fictio"),
        Pair("Genealogy", "genealogy"),
        Pair("Erotica, Erotic Romance", "erotica-erotic-romance"),
        Pair("Environmental", "environmental"),
        Pair("Eastern Africa", "eastern-africa"),
        Pair("Drawing", "drawing"),
        Pair("Diary", "diary"),
        Pair("Christian Suspense", "christian-suspense"),
        Pair("Biographies", "biographies"),
        Pair("African American Studies", "african-american-studies"),
        Pair("Young Adult Adventure", "young-adult-adventure"),
        Pair("YA Urban Fantasy", "ya-urban-fantasy"),
        Pair("YA Books", "ya-books"),
        Pair("Website Design", "website-design"),
        Pair("War & Non Fiction", "war-non-fiction"),
        Pair("Vegetarian", "vegetarian"),
        Pair("United States", "united-states"),
        Pair("Thrillers / Mystery / Crime", "thrillers-mystery-crime"),
        Pair("Spy & Espionage", "spy-espionage"),
        Pair("Snowboarding", "snowboarding"),
        Pair("Romcom", "romcom"),
        Pair("Regency England", "regency-england"),
        Pair("Productivity", "productivity"),
        Pair("Presidents", "presidents"),
        Pair("Polyamory", "polyamory"),
        Pair("Outdoors", "outdoors"),
        Pair("New Testament", "new-testament"),
        Pair("Navy", "navy"),
        Pair("Naval Historical Fiction", "naval-historical-fiction"),
        Pair("Musicals", "musicals"),
        Pair("Medieval History", "medieval-history"),
        Pair("Marvel", "marvel"),
        Pair("Intersex", "intersex"),
        Pair("Horror & Fantasy", "horror-fantasy"),
        Pair("Homeopathy", "homeopathy"),
        Pair("Harlequin Desire", "harlequin-desire"),
        Pair("Gothic Horror", "gothic-horror"),
        Pair("Gnosticism", "gnosticism"),
        Pair("Gay Male Romances", "gay-male-romances"),
        Pair("Flash Fiction", "flash-fiction"),
        Pair("Finnish Literature", "finnish-literature"),
        Pair("Fantasy Humor", "fantasy-humor"),
        Pair("European History", "european-history"),
        Pair("Ethnography", "ethnography"),
        Pair("Espionage Journalism", "espionage-journalism"),
        Pair("Espionage Fiction", "espionage-fiction"),
        Pair("Egyptology", "egyptology"),
        Pair("Crime Novels", "crime-novels"),
        Pair("Contemporary, Paranormal", "contemporary-paranormal"),
        Pair("Cocktails", "cocktails"),
        Pair("Christian Romantic Suspense", "christian-romantic-suspense"),
        Pair("Bicycles", "bicycles"),
        Pair("Aviation History", "aviation-history"),
        Pair("Australian Indigenous Author", "australian-indigenous-author"),
        Pair("Art & Photojournalism", "art-photojournalism"),
        Pair("Adult/new Adult/young Adult", "adult-new-adult-young-adult"),
        Pair("Zoology", "zoology"),
        Pair("Young & New Adult", "young-new-adult"),
        Pair("YA Horror", "ya-horror"),
        Pair("Vegan", "vegan"),
        Pair("Urban Fantasy Humor", "urban-fantasy-humor"),
        Pair("Tea", "tea"),
        Pair("Science Fiction (apocalypse/post", "science-fiction-apocalypse-post"),
        Pair("Sagas", "sagas"),
        Pair("Rome", "rome"),
        Pair("Romance & Erotica", "romance-erotica"),
        Pair("Popular History", "popular-history"),
        Pair("Paranormal Humor and Romance", "paranormal-humor-and-romance"),
        Pair("Oral History", "oral-history"),
        Pair("Older Woman/younger Man", "older-woman-younger-man"),
        Pair("New Adult/ Erotica", "new-adult-erotica"),
        Pair("Narrator", "narrator"),
        Pair("Myths & Legends", "myths-legends"),
        Pair("Mystery & Noir", "mystery-noir"),
        Pair("Music Journalism", "music-journalism"),
        Pair("Multi Genre Fiction", "multi-genre-fiction"),
        Pair("Motorcycle Romance", "motorcycle-romance"),
        Pair("Monologue", "monologue"),
        Pair("Military Espionage", "military-espionage"),
        Pair("Local History", "local-history"),
        Pair("International Affairs", "international-affairs"),
        Pair("Horse Racing", "horse-racing"),
        Pair("Historical Biography", "historical-biography"),
        Pair("Harlequin Heartwarming", "harlequin-heartwarming"),
        Pair("Gods", "gods"),
        Pair("Fantasy Erotic Romance", "fantasy-erotic-romance"),
        Pair("Electrical Engineering", "electrical-engineering"),
        Pair("Dark Erotic Romance", "dark-erotic-romance"),
        Pair("Current Affairs", "current-affairs"),
        Pair("Contemporary Romance/new Adult", "contemporary-romance-new-adult"),
        Pair("Climate Change Fiction", "climate-change-fiction"),
        Pair("Climate Change", "climate-change"),
        Pair("Civil War History", "civil-war-history"),
        Pair("Brazil", "brazil"),
        Pair("Astrophysics", "astrophysics"),
        Pair("Art Design", "art-design"),
        Pair("Zen Buddhism", "zen-buddhism"),
        Pair("Young Teens", "young-teens"),
        Pair("Young Adult Contemporary", "young-adult-contemporary"),
        Pair("Women's", "women-s"),
        Pair("Various Author", "various-author"),
        Pair("Upper YA", "upper-ya"),
        Pair("Ufology", "ufology"),
        Pair("Transgressive", "transgressive"),
        Pair("Thrillers and Suspense", "thrillers-and-suspense"),
        Pair("Thriller/suspense", "thriller-suspense"),
        Pair("Swedish Literature", "swedish-literature"),
        Pair("Spanking Fiction", "spanking-fiction"),
        Pair("Soviet Union", "soviet-union"),
        Pair("Self Mastery", "self-mastery"),
        Pair("Sci Fi / Fantasy", "sci-fi-fantasy"),
        Pair("School Stories", "school-stories"),
        Pair("Romance, Fantasy", "romance-fantasy"),
        Pair("Punk", "punk"),
        Pair("Prehistoric Fiction", "prehistoric-fiction"),
        Pair("Postmodern Literature", "postmodern-literature"),
        Pair("Political Fiction", "political-fiction"),
        Pair("Polish Literature", "polish-literature"),
        Pair("Poetry and Plays", "poetry-and-plays"),
        Pair("Plays and Drama", "plays-and-drama"),
        Pair("Parnormal Romance", "parnormal-romance"),
        Pair("Occult & Supernatural", "occult-supernatural"),
        Pair("Nutrition", "nutrition"),
        Pair("Nobel Prize", "nobel-prize"),
        Pair("New Adult Contemporary", "new-adult-contemporary"),
        Pair("Museums", "museums"),
        Pair("Monster Erotica", "monster-erotica"),
        Pair("Middle Grade/children's", "middle-grade-children-s"),
        Pair("Metaphysics", "metaphysics"),
        Pair("Memoirs", "memoirs"),
        Pair("Medicine, Chiropractic", "medicine-chiropractic"),
        Pair("Mainstream", "mainstream"),
        Pair("Linguistics and Language", "linguistics-and-language"),
        Pair("Lebanon", "lebanon"),
        Pair("Labor", "labor"),
        Pair("Kidnapping, Mystery", "kidnapping-mystery"),
        Pair("International Mystery", "international-mystery"),
        Pair("Illustrator", "illustrator"),
        Pair("Historical Romance Fiction", "historical-romance-fiction"),
        Pair("Gossip", "gossip"),
        Pair("General", "general"),
        Pair("French Literature", "french-literature"),
        Pair("Foodie", "foodie"),
        Pair("Fantasy Fiction", "fantasy-fiction"),
        Pair("Fairy Tale Retellings", "fairy-tale-retellings"),
        Pair("Dutch Literature", "dutch-literature"),
        Pair("Divorce", "divorce"),
        Pair("Detective", "detective"),
        Pair("Dark Humor", "dark-humor"),
        Pair("Culinary Cozy Mysteries", "culinary-cozy-mysteries"),
        Pair("Crime Thriller", "crime-thriller"),
        Pair("Computer Help", "computer-help"),
        Pair("Climbing", "climbing"),
        Pair("Christian Fantasy", "christian-fantasy"),
        Pair("Christian Contemporary Fiction", "christian-contemporary-fiction"),
        Pair("Cartoon", "cartoon"),
        Pair("Buisness", "buisness"),
        Pair("Beer", "beer"),
        Pair("Australian", "australian"),
        Pair("Amish Historical Romance", "amish-historical-romance"),
        Pair("African American Woman's Fiction", "african-american-woman-s-fiction"),
        Pair("Adult Contemporary", "adult-contemporary"),
        Pair("Zombie Thrillers", "zombie-thrillers"),
        Pair("YA Paranormal", "ya-paranormal"),
        Pair("Women", "women"),
        Pair("Western Africa", "western-africa"),
        Pair("Visionary Fiction", "visionary-fiction"),
        Pair("Urbanism", "urbanism"),
        Pair("Urban Studies", "urban-studies"),
        Pair("Unusual Fiction", "unusual-fiction"),
        Pair("Unicorns", "unicorns"),
        Pair("Tv Screenplays", "tv-screenplays"),
        Pair("Traditional Mystery", "traditional-mystery"),
        Pair("Social Justice", "social-justice"),
        Pair("Social History Stories,", "social-history-stories"),
        Pair("Slasher", "slasher"),
        Pair("Short Story", "short-story"),
        Pair("Short Fiction", "short-fiction"),
        Pair("Sf/fantasy", "sf-fantasy"),
        Pair("Sexy (erotic + Romance)", "sexy-erotic-romance"),
        Pair("Sex Work", "sex-work"),
        Pair("S. F.", "s-f"),
        Pair("Religion and Spirituality", "religion-and-spirituality"),
        Pair("Rabbits", "rabbits"),
        Pair("Queer Fiction", "queer-fiction"),
        Pair("Psychological", "psychological"),
        Pair("Politics, Religion, Art", "politics-religion-art"),
        Pair("Political Science & Government", "political-science-government"),
        Pair("Political Satire", "political-satire"),
        Pair("Play", "play"),
        Pair("Photographer", "photographer"),
        Pair("Paranormal, Fiction & Fantasy", "paranormal-fiction-fantasy"),
        Pair("Origami", "origami"),
        Pair("Nonfiction/true Crime", "nonfiction-true-crime"),
        Pair("Nonfiction, Fiction", "nonfiction-fiction"),
        Pair("New Adult Fantasy Romance", "new-adult-fantasy-romance"),
        Pair("Neuroscience", "neuroscience"),
        Pair("Mystery and Adventure", "mystery-and-adventure"),
        Pair("Mystery & Medical Dramas", "mystery-medical-dramas"),
        Pair("Musician", "musician"),
        Pair("Multicultural Romance", "multicultural-romance"),
        Pair("Multi Genre", "multi-genre"),
        Pair("Morocco", "morocco"),
        Pair("Mormonism", "mormonism"),
        Pair("Mm Erotic Romance", "mm-erotic-romance"),
        Pair("Metaphysical", "metaphysical"),
        Pair("Metafiction", "metafiction"),
        Pair("Mash Up", "mash-up"),
        Pair("LGBT YA", "lgbt-ya"),
        Pair("Jokes", "jokes"),
        Pair("Jane Austen Fiction", "jane-austen-fiction"),
        Pair("Israeli–palestinian Conflict", "israeli-palestinian-conflict"),
        Pair("International", "international"),
        Pair("Inspirational Fiction", "inspirational-fiction"),
        Pair("Illustrations", "illustrations"),
        Pair("Hunting", "hunting"),
        Pair("Horror ( Alex Westhaven)", "horror-alex-westhaven"),
        Pair("Historical Thriller", "historical-thriller"),
        Pair("Historical Science Fantasy", "historical-science-fantasy"),
        Pair("Historical Fiction, Literary", "historical-fiction-literary"),
        Pair("Hip Hop", "hip-hop"),
        Pair("Genderqueer", "genderqueer"),
        Pair("Film & Television", "film-television"),
        Pair("Fiction Adventure", "fiction-adventure"),
        Pair("Fiction, Nonfiction", "fiction-nonfiction"),
        Pair("Erotic Romance ( Trinity Marlow)", "erotic-romance-trinity-marlow"),
        Pair("Energy", "energy"),
        Pair("Dystopian, Dark Fantasy", "dystopian-dark-fantasy"),
        Pair("Drama, Sci Fi", "drama-sci-fi"),
        Pair("Dragon Fantasy", "dragon-fantasy"),
        Pair("Current Events", "current-events"),
        Pair("Cryptozoology", "cryptozoology"),
        Pair("Crime & Romance", "crime-romance"),
        Pair("Contemporary Fantasy", "contemporary-fantasy"),
        Pair("Computing", "computing"),
        Pair("Coloring Books", "coloring-books"),
        Pair("Catholic Fiction", "catholic-fiction"),
        Pair("Cartography", "cartography"),
        Pair("Biker Fiction", "biker-fiction"),
        Pair("Automobiles", "automobiles"),
        Pair("Artificial Intelligence", "artificial-intelligence"),
        Pair("Anthropomorphic", "anthropomorphic"),
        Pair("Activism", "activism"),
        Pair("Action & Suspense", "action-suspense"),
        Pair("17th Century", "17th-century"),
        Pair("Young Adult Urban Fantasy", "young-adult-urban-fantasy"),
        Pair("YA Paranormal Romance", "ya-paranormal-romance"),
        Pair("YA Paranormal/urban Fantasy", "ya-paranormal-urban-fantasy"),
        Pair("Wwii", "wwii"),
        Pair("Woodwork", "woodwork"),
        Pair("Women's Fiction & Humour", "women-s-fiction-humour"),
        Pair("Wine", "wine"),
        Pair("Well Being", "well-being"),
        Pair("Webcomic", "webcomic"),
        Pair("Web", "web"),
        Pair("Urban Fantasy/paranormal", "urban-fantasy-paranormal"),
        Pair("Urban Fantasy, Pnr", "urban-fantasy-pnr"),
        Pair("Turkish Literature", "turkish-literature"),
        Pair("True Crime, Biographies & Memoir", "true-crime-biographies-memoir"),
        Pair("Translator", "translator"),
        Pair("Translations", "translations"),
        Pair("Transgressive Fiction", "transgressive-fiction"),
        Pair("Trains", "trains"),
        Pair("Time Travel Fiction", "time-travel-fiction"),
        Pair("Sword & Sorcery", "sword-sorcery"),
        Pair("Suspense/thriller", "suspense-thriller"),
        Pair("Suspense, Mystery & Thrillers", "suspense-mystery-thrillers"),
        Pair("Suspense, Action, Adventure, Mod", "suspense-action-adventure-mod"),
        Pair("Strategy", "strategy"),
        Pair("Stories", "stories"),
        Pair("Spy Action Adventure", "spy-action-adventure"),
        Pair("Spanking Romance", "spanking-romance"),
        Pair("Software Guides", "software-guides"),
        Pair("Soccer", "soccer"),
        Pair("Slipstream", "slipstream"),
        Pair("Short Stories, Novellas", "short-stories-novellas"),
        Pair("Sea Creatures", "sea-creatures"),
        Pair("Screenwriter", "screenwriter"),
        Pair("Scottish Literature", "scottish-literature"),
        Pair("Science Fiction & Urban Fantasy", "science-fiction-urban-fantasy"),
        Pair("Romantic Suspense, Romantic Come", "romantic-suspense-romantic-come"),
        Pair("Romanovs", "romanovs"),
        Pair("Romance/adventure", "romance-adventure"),
        Pair("Research Methods", "research-methods"),
        Pair("Religio Philosophical Sf", "religio-philosophical-sf"),
        Pair("Regency Short Story", "regency-short-story"),
        Pair("Queer Lit", "queer-lit"),
        Pair("Princesses", "princesses"),
        Pair("Prehistory", "prehistory"),
        Pair("Poverty", "poverty"),
        Pair("Portal Fantasy", "portal-fantasy"),
        Pair("Political Economy", "political-economy"),
        Pair("Political", "political"),
        Pair("Poland", "poland"),
        Pair("Philosophical Fiction", "philosophical-fiction"),
        Pair("Paranormal & Futuristic", "paranormal-futuristic"),
        Pair("Paramormal Romance", "paramormal-romance"),
        Pair("Open To All Sexual Preferences", "open-to-all-sexual-preferences"),
        Pair("Novels, Short Stories", "novels-short-stories"),
        Pair("Novel", "novel"),
        Pair("New Age", "new-age"),
        Pair("Neurosurgery", "neurosurgery"),
        Pair("Neurology", "neurology"),
        Pair("Narrative", "narrative"),
        Pair("NSFW", "nsfw"),
        Pair("Mysteries & Thrillers", "mysteries-thrillers"),
        Pair("Multicultural", "multicultural"),
        Pair("Motivational", "motivational"),
        Pair("Monsters/fantasy", "monsters-fantasy"),
        Pair("Mixed Martial Arts", "mixed-martial-arts"),
        Pair("Metaphysical Fiction", "metaphysical-fiction"),
        Pair("Media", "media"),
        Pair("Male/male Romance", "male-male-romance"),
        Pair("Malaysian Literature", "malaysian-literature"),
        Pair("M M Science Fiction", "m-m-science-fiction"),
        Pair("Love Unvarnished", "love-unvarnished"),
        Pair("Literature and Fiction", "literature-and-fiction"),
        Pair("Lesbian Thriller", "lesbian-thriller"),
        Pair("Lesbian Military", "lesbian-military"),
        Pair("Lesbian Fantasy", "lesbian-fantasy"),
        Pair("Internet", "internet"),
        Pair("International Law", "international-law"),
        Pair("Humour, Boomer Lit", "humour-boomer-lit"),
        Pair("Human Rights", "human-rights"),
        Pair("Human Resources", "human-resources"),
        Pair("Histroical Fantasy", "histroical-fantasy"),
        Pair("Historical Gothic Fantasy", "historical-gothic-fantasy"),
        Pair("Historical & Urban Fantasy", "historical-urban-fantasy"),
        Pair("Highland Development", "highland-development"),
        Pair("Grimm", "grimm"),
        Pair("Gothic Fantasy, Dark Fantasy", "gothic-fantasy-dark-fantasy"),
        Pair("Go", "go"),
        Pair("Genealogy Mystery", "genealogy-mystery"),
        Pair("Gender & Sexuality", "gender-sexuality"),
        Pair("Gay For You", "gay-for-you"),
        Pair("French Culture", "french-culture"),
        Pair("Film History", "film-history"),
        Pair("Film Critic", "film-critic"),
        Pair("Fiction and Literature", "fiction-and-literature"),
        Pair("Fetish", "fetish"),
        Pair("Femdom Erotica", "femdom-erotica"),
        Pair("Fat", "fat"),
        Pair("Fantasía", "fantas%C3%ADa"),
        Pair("Fantasy & Sci Fi", "fantasy-sci-fi"),
        Pair("Fanfiction", "fanfiction"),
        Pair("Earth", "earth"),
        Pair("Dystopian YA, Steampunk, Uf", "dystopian-ya-steampunk-uf"),
        Pair("Dungeonpunk", "dungeonpunk"),
        Pair("Development Economics", "development-economics"),
        Pair("Denmark", "denmark"),
        Pair("Dark Fantasy/supernatural Thrill", "dark-fantasy-supernatural-thrill"),
        Pair("Dark Contemporary", "dark-contemporary"),
        Pair("Culinary Mystery", "culinary-mystery"),
        Pair("Cuckold Erotica", "cuckold-erotica"),
        Pair("Cross Dressing", "cross-dressing"),
        Pair("Critical Applied Linguistics", "critical-applied-linguistics"),
        Pair("Contemporary and Historical", "contemporary-and-historical"),
        Pair("Cinderella", "cinderella"),
        Pair("Ciencia Ficción", "ciencia-ficci%C3%B3n"),
        Pair("Booze", "booze"),
        Pair("Audiodramas", "audiodramas"),
        Pair("Asexual", "asexual"),
        Pair("Arthurian Romance", "arthurian-romance"),
        Pair("Appalachian", "appalachian"),
        Pair("Alternate Universe", "alternate-universe"),
        Pair("Alternate Earth", "alternate-earth"),
        Pair("Alchemy", "alchemy"),
        Pair("Adventure/romance", "adventure-romance"),
        Pair("Academics", "academics"),
        Pair("1st Grade", "1st-grade"),
        Pair("Young Adult, Middle Grade", "young-adult-middle-grade"),
        Pair("Young Adult, Literature & Fictio", "young-adult-literature-fictio"),
        Pair("Young Adult & Sweet New Adult", "young-adult-sweet-new-adult"),
        Pair("YA/na", "ya-na"),
        Pair("World Literature", "world-literature"),
        Pair("Women's Fiction/suspense", "women-s-fiction-suspense"),
        Pair("Wolves", "wolves"),
        Pair("War & Military", "war-military"),
        Pair("Visionary/metaphysical", "visionary-metaphysical"),
        Pair("Urban Fantasy & Fiction", "urban-fantasy-fiction"),
        Pair("Urban & Steampunk Fantasy", "urban-steampunk-fantasy"),
        Pair("Ukraine", "ukraine"),
        Pair("True Story", "true-story"),
        Pair("Traditional Regency Romance", "traditional-regency-romance"),
        Pair("Theory/philosophy", "theory-philosophy"),
        Pair("The World", "the-world"),
        Pair("Sweet Small Town Romance Series", "sweet-small-town-romance-series"),
        Pair("Surreal", "surreal"),
        Pair("Supernatural Suspense", "supernatural-suspense"),
        Pair("Superman", "superman"),
        Pair("Soldiers", "soldiers"),
        Pair("Social Theory", "social-theory"),
        Pair("Social Commentary", "social-commentary"),
        Pair("Slice Of Life", "slice-of-life"),
        Pair("Singularity", "singularity"),
        Pair("Short Story Collection", "short-story-collection"),
        Pair("Sexy Romance", "sexy-romance"),
        Pair("Sex & Sexuality", "sex-sexuality"),
        Pair("Screenwriting", "screenwriting"),
        Pair("Screenplay", "screenplay"),
        Pair("Science Nature", "science-nature"),
        Pair("Science Fiction Thriller", "science-fiction-thriller"),
        Pair("Science Fiction Romance (sfr)", "science-fiction-romance-sfr"),
        Pair("Science Fiction, Fantasy, Thrill", "science-fiction-fantasy-thrill"),
        Pair("Science Fiction & Speculative Fi", "science-fiction-speculative-fi"),
        Pair("Rus", "rus"),
        Pair("Roman Á Clef", "roman-%C3%A1-clef"),
        Pair("Romantic Fiction", "romantic-fiction"),
        Pair("Romanian Literature", "romanian-literature"),
        Pair("Rock N Roll", "rock-n-roll"),
        Pair("Risk Management", "risk-management"),
        Pair("Resumes", "resumes"),
        Pair("Religious Studies", "religious-studies"),
        Pair("Regency Romances", "regency-romances"),
        Pair("Quotation", "quotation"),
        Pair("Puzzles", "puzzles"),
        Pair("Prostitution", "prostitution"),
        Pair("Popular Music", "popular-music"),
        Pair("Political & Military Affairs", "political-military-affairs"),
        Pair("Poetry Plays", "poetry-plays"),
        Pair("Plays & Drama", "plays-drama"),
        Pair("Plants", "plants"),
        Pair("Philology", "philology"),
        Pair("Pets", "pets"),
        Pair("Pastiche", "pastiche"),
        Pair("Paranormal Romantic Suspense", "paranormal-romantic-suspense"),
        Pair("Paranormal Murder Mystery", "paranormal-murder-mystery"),
        Pair("Paranormal Mpreg Romance", "paranormal-mpreg-romance"),
        Pair("Paranormal, Sf & Fantasy", "paranormal-sf-fantasy"),
        Pair("Paranormal, Fantasy, Horror", "paranormal-fantasy-horror"),
        Pair("Paleontology", "paleontology"),
        Pair("Paleo Recipes", "paleo-recipes"),
        Pair("Palaeontology", "palaeontology"),
        Pair("Occultism", "occultism"),
        Pair("Number", "number"),
        Pair("Novellas and Short Stories", "novellas-and-short-stories"),
        Pair("Nonfiction and Creative Nonficti", "nonfiction-and-creative-nonficti"),
        Pair("Non Fiction, Theatre", "non-fiction-theatre"),
        Pair("New Weird", "new-weird"),
        Pair("New Fable", "new-fable"),
        Pair("Native Americans", "native-americans"),
        Pair("Native American History", "native-american-history"),
        Pair("Myth", "myth"),
        Pair("Mystery, Suspense, Psycho & Thri", "mystery-suspense-psycho-thri"),
        Pair("Mystery, Historical Fiction", "mystery-historical-fiction"),
        Pair("Mystery & Thrillers, Romantic Su", "mystery-thrillers-romantic-su"),
        Pair("Multicultural/interracial", "multicultural-interracial"),
        Pair("Motivational Speaker", "motivational-speaker"),
        Pair("Mills and Boon", "mills-and-boon"),
        Pair("Military, Suspense", "military-suspense"),
        Pair("Middle Grade Novel", "middle-grade-novel"),
        Pair("Menage and More", "menage-and-more"),
        Pair("Medical Non Fiction", "medical-non-fiction"),
        Pair("Mature Romance", "mature-romance"),
        Pair("Maritime", "maritime"),
        Pair("Maps", "maps"),
        Pair("Manhwa", "manhwa"),
        Pair("Magical Realism, Realistic Ficti", "magical-realism-realistic-ficti"),
        Pair("Magazine", "magazine"),
        Pair("M M Contemporary", "m-m-contemporary"),
        Pair("M/m Fiction", "m-m-fiction"),
        Pair("M/m (sometimes M/m/m)", "m-m-sometimes-m-m-m"),
        Pair("Literature & Fiction, Paranormal", "literature-fiction-paranormal"),
        Pair("Life Coach", "life-coach"),
        Pair("Librarianship", "librarianship"),
        Pair("Lesbian Romantic Thriller", "lesbian-romantic-thriller"),
        Pair("Lesbian Romantic Comedy", "lesbian-romantic-comedy"),
        Pair("Lesbian Pulp", "lesbian-pulp"),
        Pair("Lesbian Drama", "lesbian-drama"),
        Pair("Lasting Change", "lasting-change"),
        Pair("Kenya", "kenya"),
        Pair("Junior Fiction", "junior-fiction"),
        Pair("Islamism", "islamism"),
        Pair("Investing", "investing"),
        Pair("Investigative Journalism", "investigative-journalism"),
        Pair("Inspirational Romantic Suspense", "inspirational-romantic-suspense"),
        Pair("Informatics", "informatics"),
        Pair("Illustration", "illustration"),
        Pair("Illness", "illness"),
        Pair("Hungarian Literature", "hungarian-literature"),
        Pair("Hqn", "hqn"),
        Pair("Historical Gay Romance", "historical-gay-romance"),
        Pair("Historical Fiction, Young Adult", "historical-fiction-young-adult"),
        Pair("Historical Espionage, Supernatur", "historical-espionage-supernatur"),
        Pair("Historical Crime", "historical-crime"),
        Pair("Historical, Science Fiction & Fa", "historical-science-fiction-fa"),
        Pair("Historical, Inspirational", "historical-inspirational"),
        Pair("Hick Lit", "hick-lit"),
        Pair("Herbs", "herbs"),
        Pair("Health & Spirituality", "health-spirituality"),
        Pair("Hackers", "hackers"),
        Pair("Greek Mythology", "greek-mythology"),
        Pair("Gluten Free Recipes", "gluten-free-recipes"),
        Pair("Globalization and Development Is", "globalization-and-development-is"),
        Pair("Global Health", "global-health"),
        Pair("Geometry", "geometry"),
        Pair("Gender Fluidity", "gender-fluidity"),
        Pair("Gay Omegaverse", "gay-omegaverse"),
        Pair("Gay & Lesbian Romance", "gay-lesbian-romance"),
        Pair("Gamelit/litrpg", "gamelit-litrpg"),
        Pair("Foreign Correspondence", "foreign-correspondence"),
        Pair("Food, Wine, and Travel", "food-wine-and-travel"),
        Pair("Fish", "fish"),
        Pair("First Nations Literature", "first-nations-literature"),
        Pair("Film Criticism", "film-criticism"),
        Pair("Film & Tv", "film-tv"),
        Pair("Fiction and Crime", "fiction-and-crime"),
        Pair("Feminist Thrillers", "feminist-thrillers"),
        Pair("Fantasy Romances", "fantasy-romances"),
        Pair("Family Life", "family-life"),
        Pair("Family & Parenting", "family-parenting"),
        Pair("Fairytale", "fairytale"),
        Pair("Exploitation", "exploitation"),
        Pair("Existentialism", "existentialism"),
        Pair("Ethiopia", "ethiopia"),
        Pair("Essays & Memoirs", "essays-memoirs"),
        Pair("Emotion", "emotion"),
        Pair("Educational", "educational"),
        Pair("Eco Fiction", "eco-fiction"),
        Pair("Dieselpunk", "dieselpunk"),
        Pair("Devotion and Inspiration", "devotion-and-inspiration"),
        Pair("Development", "development"),
        Pair("Dark Suspense Erotica", "dark-suspense-erotica"),
        Pair("Dark Scifi / Fantasy", "dark-scifi-fantasy"),
        Pair("Dark Fantasy Romance", "dark-fantasy-romance"),
        Pair("Dark Erotica Romance", "dark-erotica-romance"),
        Pair("Dark Dominant Men", "dark-dominant-men"),
        Pair("Danish", "danish"),
        Pair("Cthulhu Mythos", "cthulhu-mythos"),
        Pair("Creationism", "creationism"),
        Pair("Counting", "counting"),
        Pair("Cornwall", "cornwall"),
        Pair("Comtemporary", "comtemporary"),
        Pair("Comedy/humor", "comedy-humor"),
        Pair("Colouring", "colouring"),
        Pair("Collapse", "collapse"),
        Pair("Collage", "collage"),
        Pair("Classic Literature", "classic-literature"),
        Pair("Cinema & Theater", "cinema-theater"),
        Pair("Children's Books and Young Adult", "children-s-books-and-young-adult"),
        Pair("Central Africa", "central-africa"),
        Pair("Catastrophism", "catastrophism"),
        Pair("Cat Sleuths", "cat-sleuths"),
        Pair("Cars", "cars"),
        Pair("Career", "career"),
        Pair("Canadian", "canadian"),
        Pair("Bulgaria", "bulgaria"),
        Pair("Book Club Fiction/literary Ficti", "book-club-fiction-literary-ficti"),
        Pair("Bolivia", "bolivia"),
        Pair("Bisexual LGBTQIA", "bisexual-lgbtqia"),
        Pair("Biochemistry", "biochemistry"),
        Pair("Batman", "batman"),
        Pair("Banking", "banking"),
        Pair("BDSM Erotic", "bdsm-erotic"),
        Pair("Atlantis", "atlantis"),
        Pair("Asian Studies", "asian-studies"),
        Pair("Archaeology and History", "archaeology-and-history"),
        Pair("Apocalypse", "apocalypse"),
        Pair("Ancient", "ancient"),
        Pair("Anarchism", "anarchism"),
        Pair("Americana", "americana"),
        Pair("American South", "american-south"),
        Pair("American Revolutionary War", "american-revolutionary-war"),
        Pair("American Libertarianism", "american-libertarianism"),
        Pair("Amateur Sleuth", "amateur-sleuth"),
        Pair("All Ages", "all-ages"),
        Pair("Alexander The Great", "alexander-the-great"),
        Pair("African Literature", "african-literature"),
        Pair("Adventure Thriller", "adventure-thriller"),
    )

    private val baseHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0"
    )

    override suspend fun loadMainPage(
        page: Int,
        mainCategory: String?,
        orderBy: String?,
        tag: String?
    ): HeadMainPageResponse {
        val url = "$mainUrl/$tag/page/$page/"
        val response = app.get(
            url, headers = baseHeaders
        )

        val document = Jsoup.parse(response.text)

        val headers = document.select("div.box_in")
        if (headers.size <= 0) return HeadMainPageResponse(url, ArrayList())
        val returnValue: ArrayList<SearchResponse> = ArrayList()
        for (h in headers) {
            val name = h?.selectFirst("h2")?.text() ?: continue
            val cUrl = h.selectFirst(" div > h2.title > a ")?.attr("href") ?: continue

            val posterUrl = h.selectFirst("div > a.highslide > img")?.attr("src")

            returnValue.add(
                SearchResponse(
                    name,
                    cUrl,
                    fixUrlNull(posterUrl),
                    null,
                    null,
                    this.name
                )
            )
        }
        return HeadMainPageResponse(url, returnValue)
    }

    override suspend fun loadHtml(url: String): String? {
        val response = app.get(url, headers = baseHeaders)
        val document = Jsoup.parse(response.text)
        document.select("div.splitnewsnavigation").remove()
        document.select("div.splitnewsnavigation2").remove()
        return document.selectFirst("#textToRead")?.html()
    }


    override suspend fun search(query: String): List<SearchResponse> {
        val response =
            app.get(
                "$mainUrl/build_in_search/?q=$query",
                headers = baseHeaders
            ) // AJAX, MIGHT ADD QUICK SEARCH

        val document = Jsoup.parse(response.text)

        val headers = document.select("div > article > div.box_in[id='search result']")

        return headers.mapNotNull { h ->
            val name = h?.selectFirst(" div > h2.title > a > b")?.text() ?: return@mapNotNull null
            val cUrl = mainUrl + h.selectFirst(" div > h2.title > a ")?.attr("href")

            val posterUrl = h.selectFirst("div > a.highslide > img")?.attr("src")

            SearchResponse(
                name,
                cUrl,
                fixUrlNull(posterUrl),
                null,
                null,
                this.name
            )
        }
    }

    override suspend fun load(url: String): LoadResponse? {
        val response = app.get(url, headers = baseHeaders)

        val document = Jsoup.parse(response.text)
        val name =
            document.selectFirst(" h2 ")?.text()?.substringBefore(", page")?.substringBefore("#")
                ?: return null

        val author =
            document.selectFirst("#dle-speedbar > div > div > ul > li:nth-child(3) > a > span")
                ?.text()

        val posterUrl =
            document.selectFirst("div.box_in > center:nth-child(1) > div > a > img")?.attr("src")

        val data: ArrayList<ChapterData> = ArrayList()
        val chapters = document.select("div.splitnewsnavigation2.ignore-select > center > div > a")

        data.add(
            ChapterData(
                "page 1",
                url.substringBeforeLast("/") + "/page,1," + url.substringAfterLast("/"),
                null,
                null
            )
        )

        for (c in 0..(chapters.size / 2)) {
            if (chapters[c].attr("href").contains("category").not()) {
                val cUrl = chapters[c].attr("href")
                val cName = "page " + chapters[c].text()
                data.add(ChapterData(cName, cUrl, null, null, null))
            }
        }

        data.sortWith { first, second ->
            if (first.name.substringAfter(" ") != second.name.substringAfter(" ")) {
                first.name.substringAfter(" ").toInt() - second.name.substringAfter(" ").toInt()
            } else {
                first.name.compareTo(second.name)
            }
        }

        return LoadResponse(
            url,
            name,
            data.distinctBy { it.url },
            author,
            fixUrlNull(posterUrl),
            null,
            null,
            null,
            null,
            null,
            null,
        )
    }
}