package com.lagradost.quicknovel.providers

import com.lagradost.quicknovel.*
import org.jsoup.Jsoup
import com.lagradost.quicknovel.MainActivity.Companion.app
import org.jsoup.nodes.Document
import java.net.HttpURLConnection
import java.net.URL

open class ReadfromnetProvider : MainAPI() {
    override val name = "ReadFrom.Net"
    override val mainUrl = "https://readfrom.net"
    override val hasMainPage = true

    override val iconId = R.drawable.icon_readfromnet

    override val iconBackgroundId = R.color.wuxiaWorldOnlineColor

    override val tags = listOf(
        "Romance" to "romance",
        "Fiction" to "fiction",
        "Fantasy" to "fantasy",
        "Young Adult" to "young-adult",
        "Contemporary" to "contemporary",
        "Mystery & Thrillers" to "mystery-thrillers",
        "Science Fiction & Fantasy" to "science-fiction-fantasy",
        "Paranormal" to "paranormal",
        "Historical Fiction" to "historical-fiction",
        "Mystery" to "mystery",
        "Science Fiction" to "science-fiction",
        "Literature & Fiction" to "literature-fiction",
        "Thriller" to "thriller",
        "Horror" to "horror",
        "Suspense" to "suspense",
        "Nonfiction" to "non-fiction",
        "Children's Books" to "children-s-books",
        "Historical" to "historical",
        "History" to "history",
        "Crime" to "crime",
        "Ebooks" to "ebooks",
        "Children's" to "children-s",
        "Chick Lit" to "chick-lit",
        "Short Stories" to "short-stories",
        "Nonfiction" to "nonfiction",
        "Humor" to "humor",
        "Poetry" to "poetry",
        "Erotica" to "erotica",
        "Humor and Comedy" to "humor-and-comedy",
        "Classics" to "classics",
        "Gay and Lesbian" to "gay-and-lesbian",
        "Biography" to "biography",
        "Childrens" to "childrens",
        "Memoir" to "memoir",
        "Adult Fiction" to "adult-fiction",
        "Biographies & Memoirs" to "biographies-memoirs",
        "New Adult" to "new-adult",
        "Gay & Lesbian" to "gay-lesbian",
        "Womens Fiction" to "womens-fiction",
        "Science" to "science",
        "Historical Romance" to "historical-romance",
        "Cultural" to "cultural",
        "Vampires" to "vampires",
        "Urban Fantasy" to "urban-fantasy",
        "Sports" to "sports",
        "Religion & Spirituality" to "religion-spirituality",
        "Paranormal Romance" to "paranormal-romance",
        "Dystopia" to "dystopia",
        "Politics" to "politics",
        "Travel" to "travel",
        "Christian Fiction" to "christian-fiction",
        "Philosophy" to "philosophy",
        "Religion" to "religion",
        "Autobiography" to "autobiography",
        "M M Romance" to "m-m-romance",
        "Cozy Mystery" to "cozy-mystery",
        "Adventure" to "adventure",
        "Comics & Graphic Novels" to "comics-graphic-novels",
        "Business" to "business",
        "Polyamorous" to "polyamorous",
        "Reverse Harem" to "reverse-harem",
        "War" to "war",
        "Writing" to "writing",
        "Self Help" to "self-help",
        "Music" to "music",
        "Art" to "art",
        "Language" to "language",
        "Westerns" to "westerns",
        "BDSM" to "bdsm",
        "Middle Grade" to "middle-grade",
        "Western" to "western",
        "Psychology" to "psychology",
        "Comics" to "comics",
        "Romantic Suspense" to "romantic-suspense",
        "Shapeshifters" to "shapeshifters",
        "Spirituality" to "spirituality",
        "Picture Books" to "picture-books",
        "Holiday" to "holiday",
        "Animals" to "animals",
        "Anthologies" to "anthologies",
        "Menage" to "menage",
        "Zombies" to "zombies",
        "Realistic Fiction" to "realistic-fiction",
        "Reference" to "reference",
        "LGBT" to "lgbt",
        "Lesbian Fiction" to "lesbian-fiction",
        "Food and Drink" to "food-and-drink",
        "Mystery Thriller" to "mystery-thriller",
        "Outdoors & Nature" to "outdoors-nature",
        "Christmas" to "christmas",
        "Sequential Art" to "sequential-art",
        "Novels" to "novels",
        "Military Fiction" to "military-fiction",
        "Graphic Novels" to "graphic-novels",
        "Post Apocalyptic" to "post-apocalyptic",
        "Apocalyptic" to "apocalyptic",
        "True Crime" to "true-crime",
        "Interracial Romance" to "interracial-romance",
        "Cookbooks" to "cookbooks",
        "Plays" to "plays",
        "Dark" to "dark",
        "Literature" to "literature",
        "GLBT" to "glbt",
        "Cooking, Food & Wine" to "cooking-food-wine",
        "Economics" to "economics",
        "Magic" to "magic",
        "Entertainment" to "entertainment",
        "Health" to "health",
        "Novella" to "novella",
        "Academic" to "academic",
        "Drama" to "drama",
        "Sociology" to "sociology",
        "Lesbian Romance" to "lesbian-romance",
        "Arts & Photography" to "arts-photography",
        "European Literature" to "european-literature",
        "Literary Fiction" to "literary-fiction",
        "African American" to "african-american",
        "Women & Gender Studies" to "women-gender-studies",
        "Adult" to "adult",
        "Steampunk" to "steampunk",
        "Time Travel" to "time-travel",
        "World War II" to "world-war-ii",
        "Erotic" to "erotic",
        "Light Novel" to "light-novel",
        "Aliens" to "aliens",
        "Urban" to "urban",
        "Women's Fiction" to "women-s-fiction",
        "Theatre" to "theatre",
        "Military History" to "military-history",
        "Health, Mind & Body" to "health-mind-body",
        "Manga" to "manga",
        "Category Romance" to "category-romance",
        "Juvenile" to "juvenile",
        "Feminism" to "feminism",
        "Canada" to "canada",
        "Lesbian" to "lesbian",
        "Essays" to "essays",
        "Science Fiction Romance" to "science-fiction-romance",
        "Social Sciences" to "social-sciences",
        "Action" to "action",
        "Media Tie In" to "media-tie-in",
        "Paranormal Fiction" to "paranormal-fiction",
        "Business & Investing" to "business-investing",
        "Environment" to "environment",
        "Regency Romance" to "regency-romance",
        "Action Adventure" to "action-adventure",
        "Magical Realism" to "magical-realism",
        "Audiobook" to "audiobook",
        "Space" to "space",
        "Regency" to "regency",
        "Parenting & Families" to "parenting-families",
        "Criticism" to "criticism",
        "Africa" to "africa",
        "Education" to "education",
        "Home & Garden" to "home-garden",
        "Alternate History" to "alternate-history",
        "Space Opera" to "space-opera",
        "Mythology" to "mythology",
        "Dragons" to "dragons",
        "Finance" to "finance",
        "Traditional Regency" to "traditional-regency",
        "Dark Romance" to "dark-romance",
        "Cooking" to "cooking",
        "Australia" to "australia",
        "Culture" to "culture",
        "Law" to "law",
        "Spy Thriller" to "spy-thriller",
        "Dark Fantasy" to "dark-fantasy",
        "Epic Fantasy" to "epic-fantasy",
        "Inspirational" to "inspirational",
        "Theology" to "theology",
        "Food" to "food",
        "Mathematics" to "mathematics",
        "Textbooks" to "textbooks",
        "Literary Criticism" to "literary-criticism",
        "Crafts" to "crafts",
        "Christianity" to "christianity",
        "Games" to "games",
        "Nature" to "nature",
        "Harem" to "harem",
        "North American Hi..." to "north-american-history",
        "Love Inspired" to "love-inspired",
        "Film" to "film",
        "African American Romance" to "african-american-romance",
        "Humanities" to "humanities",
        "School" to "school",
        "Role Playing Games" to "role-playing-games",
        "Young Adult Romance" to "young-adult-romance",
        "Professional & Technical" to "professional-technical",
        "Espionage" to "espionage",
        "Dystopian" to "dystopian",
        "Urban Fantasy Romance" to "urban-fantasy-romance",
        "Japan" to "japan",
        "Photography" to "photography",
        "Parenting" to "parenting",
        "Fairy Tales" to "fairy-tales",
        "Horses" to "horses",
        "Clean Romance" to "clean-romance",
        "France" to "france",
        "Gothic" to "gothic",
        "Abuse" to "abuse",
        "Journalism" to "journalism",
        "Biography Memoir" to "biography-memoir",
        "BDSM Romance" to "bdsm-romance",
        "Superheroes" to "superheroes",
        "Gardening" to "gardening",
        "New Adult, Historical Fiction" to "new-adult-historical-fiction",
        "Couture" to "couture",
        "Baseball" to "baseball",
        "Russia" to "russia",
        "Romantic Comedy" to "romantic-comedy",
        "Thrillers" to "thrillers",
        "Fantasy Romance" to "fantasy-romance",
        "Speculative Fiction" to "speculative-fiction",
        "Books About Books" to "books-about-books",
        "Western Romance" to "western-romance",
        "Computer Science" to "computer-science",
        "Fairies" to "fairies",
        "Crime Fiction" to "crime-fiction",
        "Young Adult, New Adult" to "young-adult-new-adult",
        "Historical Romantic Western" to "historical-romantic-western",
        "China" to "china",
        "Chapter Books" to "chapter-books",
        "Holocaust" to "holocaust",
        "Crafts & Hobbies" to "crafts-hobbies",
        "Survival" to "survival",
        "Fashion" to "fashion",
        "Historical Mystery" to "historical-mystery",
        "Ireland" to "ireland",
        "Family" to "family",
        "Medieval" to "medieval",
        "American" to "american",
        "Theater" to "theater",
        "Motorcycle" to "motorcycle",
        "Civil War" to "civil-war",
        "World War I" to "world-war-i",
        "Litrpg" to "litrpg",
        "Leadership" to "leadership",
        "Military" to "military",
        "Cozy Mysteries" to "cozy-mysteries",
        "Action Romance" to "action-romance",
        "Military Science Fiction" to "military-science-fiction",
        "Folklore" to "folklore",
        "Detective & Western" to "detective-western",
        "Architecture" to "architecture",
        "American History" to "american-history",
        "Gay" to "gay",
        "British Literature" to "british-literature",
        "Technology" to "technology",
        "Retellings" to "retellings",
        "Design" to "design",
        "Mental Health" to "mental-health",
        "Witches" to "witches",
        "Post Apocalypse" to "post-apocalypse",
        "New Adult Romance" to "new-adult-romance",
        "Football" to "football",
        "Alternative History" to "alternative-history",
        "Werewolves" to "werewolves",
        "Transport" to "transport",
        "Animal Fiction" to "animal-fiction",
        "Young Adult, New Adult, Adult" to "young-adult-new-adult-adult",
        "Queer" to "queer",
        "Computers & Internet" to "computers-internet",
        "Terrorism" to "terrorism",
        "Teaching" to "teaching",
        "New York" to "new-york",
        "Cats" to "cats",
        "Anthropology" to "anthropology",
        "Christian Romance" to "christian-romance",
        "Dogs" to "dogs",
        "Cyberpunk" to "cyberpunk",
        "Medical" to "medical",
        "Lds" to "lds",
        "Fae" to "fae",
        "Emergency Services" to "emergency-services",
        "Rock Stars" to "rock-stars",
        "Paranormal & Fantasy" to "paranormal-fantasy",
        "Occult" to "occult",
        "Weird Fiction" to "weird-fiction",
        "Dark Erotica" to "dark-erotica",
        "Culinary" to "culinary",
        "Medieval Romance" to "medieval-romance",
        "Supernatural" to "supernatural",
        "Pulp" to "pulp",
        "Intense Emotional Fiction" to "intense-emotional-fiction",
        "Noir" to "noir",
        "College" to "college",
        "BDSM and D/s" to "bdsm-and-d-s",
        "Angels" to "angels",
        "Young Adult Fiction" to "young-adult-fiction",
        "Race" to "race",
        "Buddhism" to "buddhism",
        "Satire" to "satire",
        "Physics" to "physics",
        "Love Inspired Suspense" to "love-inspired-suspense",
        "Disambiguation Profile" to "disambiguation-profile",
        "Personal Finance" to "personal-finance",
        "M F Romance" to "m-f-romance",
        "Italy" to "italy",
        "Ghost Stories" to "ghost-stories",
        "YA Mystery/suspense" to "ya-mystery-suspense",
        "Romance/suspense" to "romance-suspense",
        "Psychological Thriller" to "psychological-thriller",
        "Novelizations" to "novelizations",
        "Splatter Punk" to "splatter-punk",
        "Relationships" to "relationships",
        "Bizarro Fiction" to "bizarro-fiction",
        "Mystery and Thrillers" to "mystery-and-thrillers",
        "Ghosts" to "ghosts",
        "Engineering" to "engineering",
        "Coming Of Age" to "coming-of-age",
        "Church" to "church",
        "Archaeology" to "archaeology",
        "Programming" to "programming",
        "Linguistics" to "linguistics",
        "German Literature" to "german-literature",
        "Disambiguation" to "disambiguation",
        "Sexuality" to "sexuality",
        "Post Apocalyptic Fiction" to "post-apocalyptic-fiction",
        "Lesbian Mystery" to "lesbian-mystery",
        "Social Issues" to "social-issues",
        "Gay Romance" to "gay-romance",
        "Biology" to "biology",
        "Research" to "research",
        "Mystery & Thrillers, Particularl" to "mystery-thrillers-particularl",
        "Pirates" to "pirates",
        "Knitting" to "knitting",
        "Islam" to "islam",
        "Female Authors" to "female-authors",
        "Medicine" to "medicine",
        "Biblical Fiction" to "biblical-fiction",
        "Supernatural Thriller" to "supernatural-thriller",
        "Halloween" to "halloween",
        "Gothic Romance" to "gothic-romance",
        "Asian Literature" to "asian-literature",
        "Southern Gothic" to "southern-gothic",
        "Shifter Romance" to "shifter-romance",
        "Quilting" to "quilting",
        "Political Science" to "political-science",
        "The United States Of America" to "the-united-states-of-america",
        "Teen" to "teen",
        "Sci Fi" to "sci-fi",
        "Nurses" to "nurses",
        "Mysteries" to "mysteries",
        "BDSM Erotica" to "bdsm-erotica",
        "YA Fantasy" to "ya-fantasy",
        "Unfinished" to "unfinished",
        "Romance & Mainstream Women's Fic" to "romance-mainstream-women-s-fic",
        "Movies" to "movies",
        "Womens" to "womens",
        "Own" to "own",
        "Nursing" to "nursing",
        "Modern & Contemporary Fiction" to "modern-contemporary-fiction",
        "Historical Fantasy" to "historical-fantasy",
        "Harlequin Presents" to "harlequin-presents",
        "Comedy" to "comedy",
        "Scotland" to "scotland",
        "Omegaverse" to "omegaverse",
        "Love Stories" to "love-stories",
        "Gaming" to "gaming",
        "Sports and Games" to "sports-and-games",
        "M M F" to "m-m-f",
        "Foods" to "foods",
        "Birds" to "birds",
        "Southern Fiction" to "southern-fiction",
        "Pop Culture" to "pop-culture",
        "Murder Mystery" to "murder-mystery",
        "Humor & Comedy" to "humor-comedy",
        "Fitness" to "fitness",
        "Roman" to "roman",
        "Northern Africa" to "northern-africa",
        "Management" to "management",
        "High School" to "high-school",
        "Collections" to "collections",
        "Transgender" to "transgender",
        "Jewish" to "jewish",
        "Interracial" to "interracial",
        "Essay" to "essay",
        "Boxing" to "boxing",
        "Art History" to "art-history",
        "Young Adult Fantasy" to "young-adult-fantasy",
        "Thrillers & Suspense" to "thrillers-suspense",
        "M/m" to "m-m",
        "Judaism" to "judaism",
        "Historical Fiction, Horror" to "historical-fiction-horror",
        "High Fantasy" to "high-fantasy",
        "Fan Fiction" to "fan-fiction",
        "Family Saga" to "family-saga",
        "Storytime" to "storytime",
        "Reverse Harem Fantasy Romance" to "reverse-harem-fantasy-romance",
        "Mystery/suspense" to "mystery-suspense",
        "Israel" to "israel",
        "Humorous Contemporary Romance" to "humorous-contemporary-romance",
        "Hard Boiled" to "hard-boiled",
        "Disability" to "disability",
        "Psychological Thrillers" to "psychological-thrillers",
        "Library Science" to "library-science",
        "Lds Fiction" to "lds-fiction",
        "Irish Literature" to "irish-literature",
        "Cycling" to "cycling",
        "Computers" to "computers",
        "Catholic" to "catholic",
        "Aviation" to "aviation",
        "Atheism" to "atheism",
        "Translation" to "translation",
        "Screenplays" to "screenplays",
        "Pseudoscience" to "pseudoscience",
        "Paranormal and Fantasy" to "paranormal-and-fantasy",
        "Monsters" to "monsters",
        "Horror & Suspense" to "horror-suspense",
        "Dinosaurs" to "dinosaurs",
        "Surrealism" to "surrealism",
        "Marriage" to "marriage",
        "Astronomy" to "astronomy",
        "Historical Paranormal Romance" to "historical-paranormal-romance",
        "Dark Fiction" to "dark-fiction",
        "Theory" to "theory",
        "Romantic Erotica" to "romantic-erotica",
        "Naval History" to "naval-history",
        "Gender" to "gender",
        "Fantasy/urban Fiction" to "fantasy-urban-fiction",
        "40k" to "40k",
        "Social Science" to "social-science",
        "Reproductive Justice" to "reproductive-justice",
        "Pulp Fiction" to "pulp-fiction",
        "Narration" to "narration",
        "Military Romance" to "military-romance",
        "Literary" to "literary",
        "Hockey" to "hockey",
        "Esoterica" to "esoterica",
        "Demons" to "demons",
        "Cities" to "cities",
        "Witchcraft" to "witchcraft",
        "Technical" to "technical",
        "Mythology & Fantasy" to "mythology-fantasy",
        "Catholicism" to "catholicism",
        "African American Literature" to "african-american-literature",
        "Teen Fiction" to "teen-fiction",
        "Suspense Romance" to "suspense-romance",
        "Southern" to "southern",
        "Romantice Suspense" to "romantice-suspense",
        "Personal Development" to "personal-development",
        "Paranormal Mystery" to "paranormal-mystery",
        "Fantasy, Paranormal" to "fantasy-paranormal",
        "Cozy" to "cozy",
        "Counselling" to "counselling",
        "Billionaire Romance" to "billionaire-romance",
        "Alpha Male Romance" to "alpha-male-romance",
        "Adoption" to "adoption",
        "Women's Studies" to "women-s-studies",
        "Time Travel Romance" to "time-travel-romance",
        "Sports Romance" to "sports-romance",
        "Speculative" to "speculative",
        "Mountaineering" to "mountaineering",
        "Mafia" to "mafia",
        "Astrology" to "astrology",
        "Paranromal Romance" to "paranromal-romance",
        "Litrpg/gamelit" to "litrpg-gamelit",
        "Lesbian Erotica" to "lesbian-erotica",
        "Humour" to "humour",
        "English History" to "english-history",
        "Death" to "death",
        "Books For Young Readers" to "books-for-young-readers",
        "Scotland Set Historical Romance," to "scotland-set-historical-romance",
        "Mystery/psychological Thriller" to "mystery-psychological-thriller",
        "Mature Young Adult/ New Adult" to "mature-young-adult-new-adult",
        "Mature YA" to "mature-ya",
        "Jazz" to "jazz",
        "Greece" to "greece",
        "Geology" to "geology",
        "Folk Tales" to "folk-tales",
        "Contemp. Romance" to "contemp-romance",
        "Comic Books" to "comic-books",
        "Victorian" to "victorian",
        "Tudor Period" to "tudor-period",
        "Southern Africa" to "southern-africa",
        "Kids" to "kids",
        "Family Law" to "family-law",
        "Exploration" to "exploration",
        "Egypt" to "egypt",
        "Children's Fiction" to "children-s-fiction",
        "Asia" to "asia",
        "American Civil War" to "american-civil-war",
        "Absurdism" to "absurdism",
        "Urban Planning" to "urban-planning",
        "Splatterpunk" to "splatterpunk",
        "Several" to "several",
        "International Relations" to "international-relations",
        "Heroic Fantasy" to "heroic-fantasy",
        "Dark Romance, Dark Romantic Susp" to "dark-romance-dark-romantic-susp",
        "Communication" to "communication",
        "Civil Rights" to "civil-rights",
        "Christian Living" to "christian-living",
        "Adventures" to "adventures",
        "Wuxia" to "wuxia",
        "Psychological Romance" to "psychological-romance",
        "How To" to "how-to",
        "Contemporary & Romantic Comedy" to "contemporary-romantic-comedy",
        "Writing Craft" to "writing-craft",
        "Suspense, Paranormal Romance" to "suspense-paranormal-romance",
        "South Africa" to "south-africa",
        "Romantic" to "romantic",
        "Musicology" to "musicology",
        "Military Romantic Suspense" to "military-romantic-suspense",
        "Love" to "love",
        "Japanese Literature" to "japanese-literature",
        "Historical, Contemporary Romanc" to "historical-contemporary-romanc",
        "Gonzo Journalism" to "gonzo-journalism",
        "Geography" to "geography",
        "Fantasy,sword and Sorcery" to "fantasy-sword-and-sorcery",
        "Combat" to "combat",
        "Alcohol" to "alcohol",
        "Action/suspense Romance" to "action-suspense-romance",
        "Warfare" to "warfare",
        "Prayer" to "prayer",
        "Police" to "police",
        "Paranormal Suspence" to "paranormal-suspence",
        "Martial Arts" to "martial-arts",
        "Italian Literature" to "italian-literature",
        "Humor and Satire" to "humor-and-satire",
        "History and Military History" to "history-and-military-history",
        "Historical Fantasy Romance" to "historical-fantasy-romance",
        "Ethics" to "ethics",
        "Erotic Science Fiction & Fantasy" to "erotic-science-fiction-fantasy",
        "Epic Fantasy Romance" to "epic-fantasy-romance",
        "Contemporary Erotic" to "contemporary-erotic",
        "Buffy The Vampire Slayer" to "buffy-the-vampire-slayer",
        "Adult Paranormal Romance" to "adult-paranormal-romance",
        "Wildlife" to "wildlife",
        "Technical Trades" to "technical-trades",
        "Steamy Romance" to "steamy-romance",
        "Spirituality & Philosophy" to "spirituality-philosophy",
        "Spanish Literature" to "spanish-literature",
        "Songs, Poetry & Arts" to "songs-poetry-arts",
        "Racing" to "racing",
        "Pornography" to "pornography",
        "Pakistan" to "pakistan",
        "Mental Illness" to "mental-illness",
        "Iran" to "iran",
        "Historical Western" to "historical-western",
        "Historical Christian Romance" to "historical-christian-romance",
        "Health Care" to "health-care",
        "Graphic Novels Comics" to "graphic-novels-comics",
        "Gamebooks" to "gamebooks",
        "Fighters" to "fighters",
        "Entrepreneurship" to "entrepreneurship",
        "Domestic Fiction" to "domestic-fiction",
        "Dance" to "dance",
        "Contemporary Christian Romance" to "contemporary-christian-romance",
        "Church History" to "church-history",
        "Chess" to "chess",
        "Bizarro" to "bizarro",
        "Arthurian" to "arthurian",
        "American Revolution" to "american-revolution",
        "Urban Magic" to "urban-magic",
        "Theatre & Film" to "theatre-film",
        "Supernatural/horror" to "supernatural-horror",
        "Ornithology" to "ornithology",
        "New Adult/ Young Adult" to "new-adult-young-adult",
        "M F M" to "m-f-m",
        "Lovecraftian" to "lovecraftian",
        "LGBTQ+" to "lgbtq",
        "History Of Ideas" to "history-of-ideas",
        "Historicals, Mystery" to "historicals-mystery",
        "Highlands and Islands" to "highlands-and-islands",
        "Highland History" to "highland-history",
        "Guidebook" to "guidebook",
        "Georgian, Regency, Medieval, Sco" to "georgian-regency-medieval-sco",
        "Film Studies" to "film-studies",
        "Epic" to "epic",
        "Currency" to "currency",
        "Book Club" to "book-club",
        "YA" to "ya",
        "Supernatural Thrillers" to "supernatural-thrillers",
        "Scifi" to "scifi",
        "Sci Fi Romance" to "sci-fi-romance",
        "Legal Thriller" to "legal-thriller",
        "Historical Menage" to "historical-menage",
        "Czech Literature" to "czech-literature",
        "Calvinism" to "calvinism",
        "Bisexual" to "bisexual",
        "Zombie" to "zombie",
        "Young Adult Books" to "young-adult-books",
        "Time Slip" to "time-slip",
        "Sustainability" to "sustainability",
        "Spain" to "spain",
        "Software" to "software",
        "Social Work" to "social-work",
        "Race Studies" to "race-studies",
        "Paranormal, Contemporary" to "paranormal-contemporary",
        "Natural History" to "natural-history",
        "Money" to "money",
        "Mermaids" to "mermaids",
        "Jewish Religion" to "jewish-religion",
        "Germany" to "germany",
        "Game Novelization" to "game-novelization",
        "Fantasy / Crime / Mystery" to "fantasy-crime-mystery",
        "Erotica/ Dark Romance" to "erotica-dark-romance",
        "Erotic Suspense" to "erotic-suspense",
        "Dystopian Fiction" to "dystopian-fiction",
        "Crochet" to "crochet",
        "Contemporary Fiction" to "contemporary-fiction",
        "Contemporary Erotica" to "contemporary-erotica",
        "Confessional Erotica" to "confessional-erotica",
        "Class" to "class",
        "Celtic Fantasy/historical" to "celtic-fantasy-historical",
        "Amish Fiction" to "amish-fiction",
        "Adventure Travel" to "adventure-travel",
        "Zen" to "zen",
        "War Novels" to "war-novels",
        "Sweet Romance" to "sweet-romance",
        "Suspenseful Romance" to "suspenseful-romance",
        "Superhero" to "superhero",
        "Screenplays & Plays" to "screenplays-plays",
        "Psychoanalysis" to "psychoanalysis",
        "Plays & Screenplays" to "plays-screenplays",
        "Paranormal Erotic Romance" to "paranormal-erotic-romance",
        "New Adult, Time Travel Romance" to "new-adult-time-travel-romance",
        "Motoring" to "motoring",
        "Military Thriller" to "military-thriller",
        "Medieval Historical Romance" to "medieval-historical-romance",
        "Historical Western Romance" to "historical-western-romance",
        "Grad School" to "grad-school",
        "Gothic Romance, Urban Fantasy" to "gothic-romance-urban-fantasy",
        "Experimental" to "experimental",
        "Ecology" to "ecology",
        "Dauntless Romance" to "dauntless-romance",
        "Colouring Books" to "colouring-books",
        "Chemistry" to "chemistry",
        "Basketball" to "basketball",
        "Adult, New Adult" to "adult-new-adult",
        "Action and Adventure" to "action-and-adventure",
        "Young Adult and Adult Thrillers" to "young-adult-and-adult-thrillers",
        "Trivia" to "trivia",
        "Sewing" to "sewing",
        "Rpg" to "rpg",
        "Romance, Erotica, BDSM" to "romance-erotica-bdsm",
        "Railways" to "railways",
        "Mm" to "mm",
        "Mature Young Adult" to "mature-young-adult",
        "M M M" to "m-m-m",
        "Fiction & Literature" to "fiction-literature",
        "Fairytales" to "fairytales",
        "Erotic Historical Romance" to "erotic-historical-romance",
        "D/s Erotica" to "d-s-erotica",
        "Cultural Studies" to "cultural-studies",
        "Cinema" to "cinema",
        "BDSM Erotica. Erotic Romance" to "bdsm-erotica-erotic-romance",
        "Young Adult/tweens" to "young-adult-tweens",
        "World History" to "world-history",
        "Vampires, Shifters and Magic!" to "vampires-shifters-and-magic",
        "Tarot" to "tarot",
        "Sword and Sorcery" to "sword-and-sorcery",
        "Social" to "social",
        "Sci Fi Romance (sfr)" to "sci-fi-romance-sfr",
        "Sci/fi & Fantasy, New Adult" to "sci-fi-fantasy-new-adult",
        "Russian Literature" to "russian-literature",
        "Russian History" to "russian-history",
        "Regency Set Mystery" to "regency-set-mystery",
        "Read For School" to "read-for-school",
        "Paranormal Romance (pnr)" to "paranormal-romance-pnr",
        "Paganism" to "paganism",
        "Nonfiction, Contemporary Women's" to "nonfiction-contemporary-women-s",
        "New Pulp" to "new-pulp",
        "Nautical" to "nautical",
        "Mysticism" to "mysticism",
        "Murder" to "murder",
        "Modern" to "modern",
        "Material Culture" to "material-culture",
        "Loveswept" to "loveswept",
        "Humor/cozy" to "humor-cozy",
        "Historical Scottish Romance" to "historical-scottish-romance",
        "Green Marketing" to "green-marketing",
        "Gay Fiction" to "gay-fiction",
        "Dystopian Fantasy" to "dystopian-fantasy",
        "Dc Comics" to "dc-comics",
        "Dark Science Fiction & Fantasy" to "dark-science-fiction-fantasy",
        "Dark Historical Fiction, Mystery" to "dark-historical-fiction-mystery",
        "Cyber Fantasy" to "cyber-fantasy",
        "Contemporary Romance / Southern" to "contemporary-romance-southern",
        "Commercial Women's Fiction" to "commercial-women-s-fiction",
        "Choose Your Own Adventure" to "choose-your-own-adventure",
        "Children's, Young Adult" to "children-s-young-adult",
        "Beauty and The Beast" to "beauty-and-the-beast",
        "Applied and Social Theatre" to "applied-and-social-theatre",
        "Ancient History" to "ancient-history",
        "21st Century" to "21st-century",
        "20th Century" to "20th-century",
        "Young Adult, Late Middle Grade" to "young-adult-late-middle-grade",
        "Yaoi" to "yaoi",
        "Tragicomedy" to "tragicomedy",
        "Social Media" to "social-media",
        "Science Fiction, Cyberpunk" to "science-fiction-cyberpunk",
        "Rural" to "rural",
        "Romantic Women's Fiction & Mys" to "romantic-women-s-fiction-mys",
        "Romance! New Adult" to "romance-new-adult",
        "Real Life Experiences" to "real-life-experiences",
        "Philosophy & Spirituality" to "philosophy-spirituality",
        "New Adult, Contemporary Romance" to "new-adult-contemporary-romance",
        "Mystery, Thriller, Fantasy" to "mystery-thriller-fantasy",
        "Movie Tie Ins" to "movie-tie-ins",
        "Medievalism" to "medievalism",
        "Magick" to "magick",
        "Literature & Nonfiction" to "literature-nonfiction",
        "LGBT Romance" to "lgbt-romance",
        "Judaica" to "judaica",
        "Investigation" to "investigation",
        "Harlequin Romance" to "harlequin-romance",
        "Harlequin Blaze" to "harlequin-blaze",
        "Graphic Novel" to "graphic-novel",
        "Fantasy, Paranormal, Urban" to "fantasy-paranormal-urban",
        "English Literature" to "english-literature",
        "Doctors" to "doctors",
        "Country Noir" to "country-noir",
        "Contemporary Romance/mystery" to "contemporary-romance-mystery",
        "Conservation" to "conservation",
        "Children With Special Needs" to "children-with-special-needs",
        "Children's Picture Books" to "children-s-picture-books",
        "Canadian Literature" to "canadian-literature",
        "Australiana" to "australiana",
        "Young Adult and New Adult" to "young-adult-and-new-adult",
        "Wicca" to "wicca",
        "Videogames" to "videogames",
        "Veterinary Medicine" to "veterinary-medicine",
        "Tv" to "tv",
        "Teens, Tweens, Children, Adults" to "teens-tweens-children-adults",
        "Teachers" to "teachers",
        "Street Lit" to "street-lit",
        "Social Movements" to "social-movements",
        "Scottish Literary History" to "scottish-literary-history",
        "Science Fiction Adventure" to "science-fiction-adventure",
        "Sci Fi & Post Apocalyptic" to "sci-fi-post-apocalyptic",
        "Romantic Thriller" to "romantic-thriller",
        "Political Thriller" to "political-thriller",
        "Poetry In Scots" to "poetry-in-scots",
        "Performing Arts" to "performing-arts",
        "Paranormal Erotica" to "paranormal-erotica",
        "Paranormal, and Children's" to "paranormal-and-children-s",
        "Paranormal & Mystery Romance" to "paranormal-mystery-romance",
        "Naturalism" to "naturalism",
        "Native American" to "native-american",
        "Mythological/historical Fiction" to "mythological-historical-fiction",
        "Mystery, Suspense, & Thrillers" to "mystery-suspense-thrillers",
        "Mystery & Crime" to "mystery-crime",
        "Mail Order Brides" to "mail-order-brides",
        "Lighthearted Adventures" to "lighthearted-adventures",
        "Inspirational Western Romance" to "inspirational-western-romance",
        "Indian Literature" to "indian-literature",
        "Gay and Lesbian, M/f" to "gay-and-lesbian-m-f",
        "Futuristic" to "futuristic",
        "Fostering" to "fostering",
        "Firearms" to "firearms",
        "Field Guides" to "field-guides",
        "Fantasy, Sci Fi & Horror" to "fantasy-sci-fi-horror",
        "Erotic Fiction" to "erotic-fiction",
        "Diaries" to "diaries",
        "Contemporary Romance and Erotica" to "contemporary-romance-and-erotica",
        "African Studies" to "african-studies",
        "African American Fiction" to "african-american-fiction",
        "Young Adult Paranormal Romance" to "young-adult-paranormal-romance",
        "Young Adult, Mainstream" to "young-adult-mainstream",
        "Visual Art" to "visual-art",
        "Video Games" to "video-games",
        "Soft Porn" to "soft-porn",
        "Science Fiction and Fantasy" to "science-fiction-and-fantasy",
        "Saga" to "saga",
        "Romantic Suspense & Fantasy" to "romantic-suspense-fantasy",
        "Romania" to "romania",
        "Romance and Erotic Romance" to "romance-and-erotic-romance",
        "Romance Thriller Suspense" to "romance-thriller-suspense",
        "Roleplaying Games" to "roleplaying-games",
        "Preservation" to "preservation",
        "Paranormal Romance & Fantasy Rom" to "paranormal-romance-fantasy-rom",
        "Mythic Fantasy" to "mythic-fantasy",
        "Mystery & Adventure" to "mystery-adventure",
        "Museology" to "museology",
        "Mm Romance" to "mm-romance",
        "Military Art & Science" to "military-art-science",
        "Military/war" to "military-war",
        "History/alternate History Fictio" to "history-alternate-history-fictio",
        "Genealogy" to "genealogy",
        "Erotica, Erotic Romance" to "erotica-erotic-romance",
        "Environmental" to "environmental",
        "Eastern Africa" to "eastern-africa",
        "Drawing" to "drawing",
        "Diary" to "diary",
        "Christian Suspense" to "christian-suspense",
        "Biographies" to "biographies",
        "African American Studies" to "african-american-studies",
        "Young Adult Adventure" to "young-adult-adventure",
        "YA Urban Fantasy" to "ya-urban-fantasy",
        "YA Books" to "ya-books",
        "Website Design" to "website-design",
        "War & Non Fiction" to "war-non-fiction",
        "Vegetarian" to "vegetarian",
        "United States" to "united-states",
        "Thrillers / Mystery / Crime" to "thrillers-mystery-crime",
        "Spy & Espionage" to "spy-espionage",
        "Snowboarding" to "snowboarding",
        "Romcom" to "romcom",
        "Regency England" to "regency-england",
        "Productivity" to "productivity",
        "Presidents" to "presidents",
        "Polyamory" to "polyamory",
        "Outdoors" to "outdoors",
        "New Testament" to "new-testament",
        "Navy" to "navy",
        "Naval Historical Fiction" to "naval-historical-fiction",
        "Musicals" to "musicals",
        "Medieval History" to "medieval-history",
        "Marvel" to "marvel",
        "Intersex" to "intersex",
        "Horror & Fantasy" to "horror-fantasy",
        "Homeopathy" to "homeopathy",
        "Harlequin Desire" to "harlequin-desire",
        "Gothic Horror" to "gothic-horror",
        "Gnosticism" to "gnosticism",
        "Gay Male Romances" to "gay-male-romances",
        "Flash Fiction" to "flash-fiction",
        "Finnish Literature" to "finnish-literature",
        "Fantasy Humor" to "fantasy-humor",
        "European History" to "european-history",
        "Ethnography" to "ethnography",
        "Espionage Journalism" to "espionage-journalism",
        "Espionage Fiction" to "espionage-fiction",
        "Egyptology" to "egyptology",
        "Crime Novels" to "crime-novels",
        "Contemporary, Paranormal" to "contemporary-paranormal",
        "Cocktails" to "cocktails",
        "Christian Romantic Suspense" to "christian-romantic-suspense",
        "Bicycles" to "bicycles",
        "Aviation History" to "aviation-history",
        "Australian Indigenous Author" to "australian-indigenous-author",
        "Art & Photojournalism" to "art-photojournalism",
        "Adult/new Adult/young Adult" to "adult-new-adult-young-adult",
        "Zoology" to "zoology",
        "Young & New Adult" to "young-new-adult",
        "YA Horror" to "ya-horror",
        "Vegan" to "vegan",
        "Urban Fantasy Humor" to "urban-fantasy-humor",
        "Tea" to "tea",
        "Science Fiction (apocalypse/post" to "science-fiction-apocalypse-post",
        "Sagas" to "sagas",
        "Rome" to "rome",
        "Romance & Erotica" to "romance-erotica",
        "Popular History" to "popular-history",
        "Paranormal Humor and Romance" to "paranormal-humor-and-romance",
        "Oral History" to "oral-history",
        "Older Woman/younger Man" to "older-woman-younger-man",
        "New Adult/ Erotica" to "new-adult-erotica",
        "Narrator" to "narrator",
        "Myths & Legends" to "myths-legends",
        "Mystery & Noir" to "mystery-noir",
        "Music Journalism" to "music-journalism",
        "Multi Genre Fiction" to "multi-genre-fiction",
        "Motorcycle Romance" to "motorcycle-romance",
        "Monologue" to "monologue",
        "Military Espionage" to "military-espionage",
        "Local History" to "local-history",
        "International Affairs" to "international-affairs",
        "Horse Racing" to "horse-racing",
        "Historical Biography" to "historical-biography",
        "Harlequin Heartwarming" to "harlequin-heartwarming",
        "Gods" to "gods",
        "Fantasy Erotic Romance" to "fantasy-erotic-romance",
        "Electrical Engineering" to "electrical-engineering",
        "Dark Erotic Romance" to "dark-erotic-romance",
        "Current Affairs" to "current-affairs",
        "Contemporary Romance/new Adult" to "contemporary-romance-new-adult",
        "Climate Change Fiction" to "climate-change-fiction",
        "Climate Change" to "climate-change",
        "Civil War History" to "civil-war-history",
        "Brazil" to "brazil",
        "Astrophysics" to "astrophysics",
        "Art Design" to "art-design",
        "Zen Buddhism" to "zen-buddhism",
        "Young Teens" to "young-teens",
        "Young Adult Contemporary" to "young-adult-contemporary",
        "Women's" to "women-s",
        "Various Author" to "various-author",
        "Upper YA" to "upper-ya",
        "Ufology" to "ufology",
        "Transgressive" to "transgressive",
        "Thrillers and Suspense" to "thrillers-and-suspense",
        "Thriller/suspense" to "thriller-suspense",
        "Swedish Literature" to "swedish-literature",
        "Spanking Fiction" to "spanking-fiction",
        "Soviet Union" to "soviet-union",
        "Self Mastery" to "self-mastery",
        "Sci Fi / Fantasy" to "sci-fi-fantasy",
        "School Stories" to "school-stories",
        "Romance, Fantasy" to "romance-fantasy",
        "Punk" to "punk",
        "Prehistoric Fiction" to "prehistoric-fiction",
        "Postmodern Literature" to "postmodern-literature",
        "Political Fiction" to "political-fiction",
        "Polish Literature" to "polish-literature",
        "Poetry and Plays" to "poetry-and-plays",
        "Plays and Drama" to "plays-and-drama",
        "Parnormal Romance" to "parnormal-romance",
        "Occult & Supernatural" to "occult-supernatural",
        "Nutrition" to "nutrition",
        "Nobel Prize" to "nobel-prize",
        "New Adult Contemporary" to "new-adult-contemporary",
        "Museums" to "museums",
        "Monster Erotica" to "monster-erotica",
        "Middle Grade/children's" to "middle-grade-children-s",
        "Metaphysics" to "metaphysics",
        "Memoirs" to "memoirs",
        "Medicine, Chiropractic" to "medicine-chiropractic",
        "Mainstream" to "mainstream",
        "Linguistics and Language" to "linguistics-and-language",
        "Lebanon" to "lebanon",
        "Labor" to "labor",
        "Kidnapping, Mystery" to "kidnapping-mystery",
        "International Mystery" to "international-mystery",
        "Illustrator" to "illustrator",
        "Historical Romance Fiction" to "historical-romance-fiction",
        "Gossip" to "gossip",
        "General" to "general",
        "French Literature" to "french-literature",
        "Foodie" to "foodie",
        "Fantasy Fiction" to "fantasy-fiction",
        "Fairy Tale Retellings" to "fairy-tale-retellings",
        "Dutch Literature" to "dutch-literature",
        "Divorce" to "divorce",
        "Detective" to "detective",
        "Dark Humor" to "dark-humor",
        "Culinary Cozy Mysteries" to "culinary-cozy-mysteries",
        "Crime Thriller" to "crime-thriller",
        "Computer Help" to "computer-help",
        "Climbing" to "climbing",
        "Christian Fantasy" to "christian-fantasy",
        "Christian Contemporary Fiction" to "christian-contemporary-fiction",
        "Cartoon" to "cartoon",
        "Buisness" to "buisness",
        "Beer" to "beer",
        "Australian" to "australian",
        "Amish Historical Romance" to "amish-historical-romance",
        "African American Woman's Fiction" to "african-american-woman-s-fiction",
        "Adult Contemporary" to "adult-contemporary",
        "Zombie Thrillers" to "zombie-thrillers",
        "YA Paranormal" to "ya-paranormal",
        "Women" to "women",
        "Western Africa" to "western-africa",
        "Visionary Fiction" to "visionary-fiction",
        "Urbanism" to "urbanism",
        "Urban Studies" to "urban-studies",
        "Unusual Fiction" to "unusual-fiction",
        "Unicorns" to "unicorns",
        "Tv Screenplays" to "tv-screenplays",
        "Traditional Mystery" to "traditional-mystery",
        "Social Justice" to "social-justice",
        "Social History Stories," to "social-history-stories",
        "Slasher" to "slasher",
        "Short Story" to "short-story",
        "Short Fiction" to "short-fiction",
        "Sf/fantasy" to "sf-fantasy",
        "Sexy (erotic + Romance)" to "sexy-erotic-romance",
        "Sex Work" to "sex-work",
        "S. F." to "s-f",
        "Religion and Spirituality" to "religion-and-spirituality",
        "Rabbits" to "rabbits",
        "Queer Fiction" to "queer-fiction",
        "Psychological" to "psychological",
        "Politics, Religion, Art" to "politics-religion-art",
        "Political Science & Government" to "political-science-government",
        "Political Satire" to "political-satire",
        "Play" to "play",
        "Photographer" to "photographer",
        "Paranormal, Fiction & Fantasy" to "paranormal-fiction-fantasy",
        "Origami" to "origami",
        "Nonfiction/true Crime" to "nonfiction-true-crime",
        "Nonfiction, Fiction" to "nonfiction-fiction",
        "New Adult Fantasy Romance" to "new-adult-fantasy-romance",
        "Neuroscience" to "neuroscience",
        "Mystery and Adventure" to "mystery-and-adventure",
        "Mystery & Medical Dramas" to "mystery-medical-dramas",
        "Musician" to "musician",
        "Multicultural Romance" to "multicultural-romance",
        "Multi Genre" to "multi-genre",
        "Morocco" to "morocco",
        "Mormonism" to "mormonism",
        "Mm Erotic Romance" to "mm-erotic-romance",
        "Metaphysical" to "metaphysical",
        "Metafiction" to "metafiction",
        "Mash Up" to "mash-up",
        "LGBT YA" to "lgbt-ya",
        "Jokes" to "jokes",
        "Jane Austen Fiction" to "jane-austen-fiction",
        "Israeli–palestinian Conflict" to "israeli-palestinian-conflict",
        "International" to "international",
        "Inspirational Fiction" to "inspirational-fiction",
        "Illustrations" to "illustrations",
        "Hunting" to "hunting",
        "Horror ( Alex Westhaven)" to "horror-alex-westhaven",
        "Historical Thriller" to "historical-thriller",
        "Historical Science Fantasy" to "historical-science-fantasy",
        "Historical Fiction, Literary" to "historical-fiction-literary",
        "Hip Hop" to "hip-hop",
        "Genderqueer" to "genderqueer",
        "Film & Television" to "film-television",
        "Fiction Adventure" to "fiction-adventure",
        "Fiction, Nonfiction" to "fiction-nonfiction",
        "Erotic Romance ( Trinity Marlow)" to "erotic-romance-trinity-marlow",
        "Energy" to "energy",
        "Dystopian, Dark Fantasy" to "dystopian-dark-fantasy",
        "Drama, Sci Fi" to "drama-sci-fi",
        "Dragon Fantasy" to "dragon-fantasy",
        "Current Events" to "current-events",
        "Cryptozoology" to "cryptozoology",
        "Crime & Romance" to "crime-romance",
        "Contemporary Fantasy" to "contemporary-fantasy",
        "Computing" to "computing",
        "Coloring Books" to "coloring-books",
        "Catholic Fiction" to "catholic-fiction",
        "Cartography" to "cartography",
        "Biker Fiction" to "biker-fiction",
        "Automobiles" to "automobiles",
        "Artificial Intelligence" to "artificial-intelligence",
        "Anthropomorphic" to "anthropomorphic",
        "Activism" to "activism",
        "Action & Suspense" to "action-suspense",
        "17th Century" to "17th-century",
        "Young Adult Urban Fantasy" to "young-adult-urban-fantasy",
        "YA Paranormal Romance" to "ya-paranormal-romance",
        "YA Paranormal/urban Fantasy" to "ya-paranormal-urban-fantasy",
        "Wwii" to "wwii",
        "Woodwork" to "woodwork",
        "Women's Fiction & Humour" to "women-s-fiction-humour",
        "Wine" to "wine",
        "Well Being" to "well-being",
        "Webcomic" to "webcomic",
        "Web" to "web",
        "Urban Fantasy/paranormal" to "urban-fantasy-paranormal",
        "Urban Fantasy, Pnr" to "urban-fantasy-pnr",
        "Turkish Literature" to "turkish-literature",
        "True Crime, Biographies & Memoir" to "true-crime-biographies-memoir",
        "Translator" to "translator",
        "Translations" to "translations",
        "Transgressive Fiction" to "transgressive-fiction",
        "Trains" to "trains",
        "Time Travel Fiction" to "time-travel-fiction",
        "Sword & Sorcery" to "sword-sorcery",
        "Suspense/thriller" to "suspense-thriller",
        "Suspense, Mystery & Thrillers" to "suspense-mystery-thrillers",
        "Suspense, Action, Adventure, Mod" to "suspense-action-adventure-mod",
        "Strategy" to "strategy",
        "Stories" to "stories",
        "Spy Action Adventure" to "spy-action-adventure",
        "Spanking Romance" to "spanking-romance",
        "Software Guides" to "software-guides",
        "Soccer" to "soccer",
        "Slipstream" to "slipstream",
        "Short Stories, Novellas" to "short-stories-novellas",
        "Sea Creatures" to "sea-creatures",
        "Screenwriter" to "screenwriter",
        "Scottish Literature" to "scottish-literature",
        "Science Fiction & Urban Fantasy" to "science-fiction-urban-fantasy",
        "Romantic Suspense, Romantic Come" to "romantic-suspense-romantic-come",
        "Romanovs" to "romanovs",
        "Romance/adventure" to "romance-adventure",
        "Research Methods" to "research-methods",
        "Religio Philosophical Sf" to "religio-philosophical-sf",
        "Regency Short Story" to "regency-short-story",
        "Queer Lit" to "queer-lit",
        "Princesses" to "princesses",
        "Prehistory" to "prehistory",
        "Poverty" to "poverty",
        "Portal Fantasy" to "portal-fantasy",
        "Political Economy" to "political-economy",
        "Political" to "political",
        "Poland" to "poland",
        "Philosophical Fiction" to "philosophical-fiction",
        "Paranormal & Futuristic" to "paranormal-futuristic",
        "Paramormal Romance" to "paramormal-romance",
        "Open To All Sexual Preferences" to "open-to-all-sexual-preferences",
        "Novels, Short Stories" to "novels-short-stories",
        "Novel" to "novel",
        "New Age" to "new-age",
        "Neurosurgery" to "neurosurgery",
        "Neurology" to "neurology",
        "Narrative" to "narrative",
        "NSFW" to "nsfw",
        "Mysteries & Thrillers" to "mysteries-thrillers",
        "Multicultural" to "multicultural",
        "Motivational" to "motivational",
        "Monsters/fantasy" to "monsters-fantasy",
        "Mixed Martial Arts" to "mixed-martial-arts",
        "Metaphysical Fiction" to "metaphysical-fiction",
        "Media" to "media",
        "Male/male Romance" to "male-male-romance",
        "Malaysian Literature" to "malaysian-literature",
        "M M Science Fiction" to "m-m-science-fiction",
        "Love Unvarnished" to "love-unvarnished",
        "Literature and Fiction" to "literature-and-fiction",
        "Lesbian Thriller" to "lesbian-thriller",
        "Lesbian Military" to "lesbian-military",
        "Lesbian Fantasy" to "lesbian-fantasy",
        "Internet" to "internet",
        "International Law" to "international-law",
        "Humour, Boomer Lit" to "humour-boomer-lit",
        "Human Rights" to "human-rights",
        "Human Resources" to "human-resources",
        "Histroical Fantasy" to "histroical-fantasy",
        "Historical Gothic Fantasy" to "historical-gothic-fantasy",
        "Historical & Urban Fantasy" to "historical-urban-fantasy",
        "Highland Development" to "highland-development",
        "Grimm" to "grimm",
        "Gothic Fantasy, Dark Fantasy" to "gothic-fantasy-dark-fantasy",
        "Go" to "go",
        "Genealogy Mystery" to "genealogy-mystery",
        "Gender & Sexuality" to "gender-sexuality",
        "Gay For You" to "gay-for-you",
        "French Culture" to "french-culture",
        "Film History" to "film-history",
        "Film Critic" to "film-critic",
        "Fiction and Literature" to "fiction-and-literature",
        "Fetish" to "fetish",
        "Femdom Erotica" to "femdom-erotica",
        "Fat" to "fat",
        "Fantasía" to "fantas%C3%ADa",
        "Fantasy & Sci Fi" to "fantasy-sci-fi",
        "Fanfiction" to "fanfiction",
        "Earth" to "earth",
        "Dystopian YA, Steampunk, Uf" to "dystopian-ya-steampunk-uf",
        "Dungeonpunk" to "dungeonpunk",
        "Development Economics" to "development-economics",
        "Denmark" to "denmark",
        "Dark Fantasy/supernatural Thrill" to "dark-fantasy-supernatural-thrill",
        "Dark Contemporary" to "dark-contemporary",
        "Culinary Mystery" to "culinary-mystery",
        "Cuckold Erotica" to "cuckold-erotica",
        "Cross Dressing" to "cross-dressing",
        "Critical Applied Linguistics" to "critical-applied-linguistics",
        "Contemporary and Historical" to "contemporary-and-historical",
        "Cinderella" to "cinderella",
        "Ciencia Ficción" to "ciencia-ficci%C3%B3n",
        "Booze" to "booze",
        "Audiodramas" to "audiodramas",
        "Asexual" to "asexual",
        "Arthurian Romance" to "arthurian-romance",
        "Appalachian" to "appalachian",
        "Alternate Universe" to "alternate-universe",
        "Alternate Earth" to "alternate-earth",
        "Alchemy" to "alchemy",
        "Adventure/romance" to "adventure-romance",
        "Academics" to "academics",
        "1st Grade" to "1st-grade",
        "Young Adult, Middle Grade" to "young-adult-middle-grade",
        "Young Adult, Literature & Fictio" to "young-adult-literature-fictio",
        "Young Adult & Sweet New Adult" to "young-adult-sweet-new-adult",
        "YA/na" to "ya-na",
        "World Literature" to "world-literature",
        "Women's Fiction/suspense" to "women-s-fiction-suspense",
        "Wolves" to "wolves",
        "War & Military" to "war-military",
        "Visionary/metaphysical" to "visionary-metaphysical",
        "Urban Fantasy & Fiction" to "urban-fantasy-fiction",
        "Urban & Steampunk Fantasy" to "urban-steampunk-fantasy",
        "Ukraine" to "ukraine",
        "True Story" to "true-story",
        "Traditional Regency Romance" to "traditional-regency-romance",
        "Theory/philosophy" to "theory-philosophy",
        "The World" to "the-world",
        "Sweet Small Town Romance Series" to "sweet-small-town-romance-series",
        "Surreal" to "surreal",
        "Supernatural Suspense" to "supernatural-suspense",
        "Superman" to "superman",
        "Soldiers" to "soldiers",
        "Social Theory" to "social-theory",
        "Social Commentary" to "social-commentary",
        "Slice Of Life" to "slice-of-life",
        "Singularity" to "singularity",
        "Short Story Collection" to "short-story-collection",
        "Sexy Romance" to "sexy-romance",
        "Sex & Sexuality" to "sex-sexuality",
        "Screenwriting" to "screenwriting",
        "Screenplay" to "screenplay",
        "Science Nature" to "science-nature",
        "Science Fiction Thriller" to "science-fiction-thriller",
        "Science Fiction Romance (sfr)" to "science-fiction-romance-sfr",
        "Science Fiction, Fantasy, Thrill" to "science-fiction-fantasy-thrill",
        "Science Fiction & Speculative Fi" to "science-fiction-speculative-fi",
        "Rus" to "rus",
        "Roman Á Clef" to "roman-%C3%A1-clef",
        "Romantic Fiction" to "romantic-fiction",
        "Romanian Literature" to "romanian-literature",
        "Rock N Roll" to "rock-n-roll",
        "Risk Management" to "risk-management",
        "Resumes" to "resumes",
        "Religious Studies" to "religious-studies",
        "Regency Romances" to "regency-romances",
        "Quotation" to "quotation",
        "Puzzles" to "puzzles",
        "Prostitution" to "prostitution",
        "Popular Music" to "popular-music",
        "Political & Military Affairs" to "political-military-affairs",
        "Poetry Plays" to "poetry-plays",
        "Plays & Drama" to "plays-drama",
        "Plants" to "plants",
        "Philology" to "philology",
        "Pets" to "pets",
        "Pastiche" to "pastiche",
        "Paranormal Romantic Suspense" to "paranormal-romantic-suspense",
        "Paranormal Murder Mystery" to "paranormal-murder-mystery",
        "Paranormal Mpreg Romance" to "paranormal-mpreg-romance",
        "Paranormal, Sf & Fantasy" to "paranormal-sf-fantasy",
        "Paranormal, Fantasy, Horror" to "paranormal-fantasy-horror",
        "Paleontology" to "paleontology",
        "Paleo Recipes" to "paleo-recipes",
        "Palaeontology" to "palaeontology",
        "Occultism" to "occultism",
        "Number" to "number",
        "Novellas and Short Stories" to "novellas-and-short-stories",
        "Nonfiction and Creative Nonficti" to "nonfiction-and-creative-nonficti",
        "Non Fiction, Theatre" to "non-fiction-theatre",
        "New Weird" to "new-weird",
        "New Fable" to "new-fable",
        "Native Americans" to "native-americans",
        "Native American History" to "native-american-history",
        "Myth" to "myth",
        "Mystery, Suspense, Psycho & Thri" to "mystery-suspense-psycho-thri",
        "Mystery, Historical Fiction" to "mystery-historical-fiction",
        "Mystery & Thrillers, Romantic Su" to "mystery-thrillers-romantic-su",
        "Multicultural/interracial" to "multicultural-interracial",
        "Motivational Speaker" to "motivational-speaker",
        "Mills and Boon" to "mills-and-boon",
        "Military, Suspense" to "military-suspense",
        "Middle Grade Novel" to "middle-grade-novel",
        "Menage and More" to "menage-and-more",
        "Medical Non Fiction" to "medical-non-fiction",
        "Mature Romance" to "mature-romance",
        "Maritime" to "maritime",
        "Maps" to "maps",
        "Manhwa" to "manhwa",
        "Magical Realism, Realistic Ficti" to "magical-realism-realistic-ficti",
        "Magazine" to "magazine",
        "M M Contemporary" to "m-m-contemporary",
        "M/m Fiction" to "m-m-fiction",
        "M/m (sometimes M/m/m)" to "m-m-sometimes-m-m-m",
        "Literature & Fiction, Paranormal" to "literature-fiction-paranormal",
        "Life Coach" to "life-coach",
        "Librarianship" to "librarianship",
        "Lesbian Romantic Thriller" to "lesbian-romantic-thriller",
        "Lesbian Romantic Comedy" to "lesbian-romantic-comedy",
        "Lesbian Pulp" to "lesbian-pulp",
        "Lesbian Drama" to "lesbian-drama",
        "Lasting Change" to "lasting-change",
        "Kenya" to "kenya",
        "Junior Fiction" to "junior-fiction",
        "Islamism" to "islamism",
        "Investing" to "investing",
        "Investigative Journalism" to "investigative-journalism",
        "Inspirational Romantic Suspense" to "inspirational-romantic-suspense",
        "Informatics" to "informatics",
        "Illustration" to "illustration",
        "Illness" to "illness",
        "Hungarian Literature" to "hungarian-literature",
        "Hqn" to "hqn",
        "Historical Gay Romance" to "historical-gay-romance",
        "Historical Fiction, Young Adult" to "historical-fiction-young-adult",
        "Historical Espionage, Supernatur" to "historical-espionage-supernatur",
        "Historical Crime" to "historical-crime",
        "Historical, Science Fiction & Fa" to "historical-science-fiction-fa",
        "Historical, Inspirational" to "historical-inspirational",
        "Hick Lit" to "hick-lit",
        "Herbs" to "herbs",
        "Health & Spirituality" to "health-spirituality",
        "Hackers" to "hackers",
        "Greek Mythology" to "greek-mythology",
        "Gluten Free Recipes" to "gluten-free-recipes",
        "Globalization and Development Is" to "globalization-and-development-is",
        "Global Health" to "global-health",
        "Geometry" to "geometry",
        "Gender Fluidity" to "gender-fluidity",
        "Gay Omegaverse" to "gay-omegaverse",
        "Gay & Lesbian Romance" to "gay-lesbian-romance",
        "Gamelit/litrpg" to "gamelit-litrpg",
        "Foreign Correspondence" to "foreign-correspondence",
        "Food, Wine, and Travel" to "food-wine-and-travel",
        "Fish" to "fish",
        "First Nations Literature" to "first-nations-literature",
        "Film Criticism" to "film-criticism",
        "Film & Tv" to "film-tv",
        "Fiction and Crime" to "fiction-and-crime",
        "Feminist Thrillers" to "feminist-thrillers",
        "Fantasy Romances" to "fantasy-romances",
        "Family Life" to "family-life",
        "Family & Parenting" to "family-parenting",
        "Fairytale" to "fairytale",
        "Exploitation" to "exploitation",
        "Existentialism" to "existentialism",
        "Ethiopia" to "ethiopia",
        "Essays & Memoirs" to "essays-memoirs",
        "Emotion" to "emotion",
        "Educational" to "educational",
        "Eco Fiction" to "eco-fiction",
        "Dieselpunk" to "dieselpunk",
        "Devotion and Inspiration" to "devotion-and-inspiration",
        "Development" to "development",
        "Dark Suspense Erotica" to "dark-suspense-erotica",
        "Dark Scifi / Fantasy" to "dark-scifi-fantasy",
        "Dark Fantasy Romance" to "dark-fantasy-romance",
        "Dark Erotica Romance" to "dark-erotica-romance",
        "Dark Dominant Men" to "dark-dominant-men",
        "Danish" to "danish",
        "Cthulhu Mythos" to "cthulhu-mythos",
        "Creationism" to "creationism",
        "Counting" to "counting",
        "Cornwall" to "cornwall",
        "Comtemporary" to "comtemporary",
        "Comedy/humor" to "comedy-humor",
        "Colouring" to "colouring",
        "Collapse" to "collapse",
        "Collage" to "collage",
        "Classic Literature" to "classic-literature",
        "Cinema & Theater" to "cinema-theater",
        "Children's Books and Young Adult" to "children-s-books-and-young-adult",
        "Central Africa" to "central-africa",
        "Catastrophism" to "catastrophism",
        "Cat Sleuths" to "cat-sleuths",
        "Cars" to "cars",
        "Career" to "career",
        "Canadian" to "canadian",
        "Bulgaria" to "bulgaria",
        "Book Club Fiction/literary Ficti" to "book-club-fiction-literary-ficti",
        "Bolivia" to "bolivia",
        "Bisexual LGBTQIA" to "bisexual-lgbtqia",
        "Biochemistry" to "biochemistry",
        "Batman" to "batman",
        "Banking" to "banking",
        "BDSM Erotic" to "bdsm-erotic",
        "Atlantis" to "atlantis",
        "Asian Studies" to "asian-studies",
        "Archaeology and History" to "archaeology-and-history",
        "Apocalypse" to "apocalypse",
        "Ancient" to "ancient",
        "Anarchism" to "anarchism",
        "Americana" to "americana",
        "American South" to "american-south",
        "American Revolutionary War" to "american-revolutionary-war",
        "American Libertarianism" to "american-libertarianism",
        "Amateur Sleuth" to "amateur-sleuth",
        "All Ages" to "all-ages",
        "Alexander The Great" to "alexander-the-great",
        "African Literature" to "african-literature",
        "Adventure Thriller" to "adventure-thriller",
    ).sortedBy { it.first }.let { listOf("All" to "allbooks") + it }

    private val baseHeaders = mapOf(
        "user-agent" to "Mozilla/5.0"
    )


    override suspend fun loadMainPage(
        page: Int,
        mainCategory: String?,
        orderBy: String?,
        tag: String?
    ): HeadMainPageResponse {
        val url = "$mainUrl/$tag/page/$page/"
        val response = app.get(url, headers = baseHeaders).document
        val returnValue = response.select("div.box_in").mapNotNull { h ->
            val name = h.selectFirst("h2")?.text() ?: return@mapNotNull null
            val cUrl = h.selectFirst(" div > h2.title > a ")?.attr("href") ?: return@mapNotNull null

            newSearchResponse(name = name, url = cUrl) {
                posterHeaders = baseHeaders
                posterUrl = fixUrlNull(h.selectFirst("div > a.highslide > img")?.attr("src"))
            }
        }



        return HeadMainPageResponse(url, returnValue)
    }

    override suspend fun loadHtml(url: String): String? {
        val document = app.get(url, headers = baseHeaders).document
        document.select("div.splitnewsnavigation").remove()
        document.select("div.splitnewsnavigation2").remove()
        return  document.selectFirst("#textToRead")?.html()
    }

    override suspend fun search(query: String): List<SearchResponse> {
        val document = app.get("$mainUrl/build_in_search/?q=$query", headers = baseHeaders).document
        val headers = document.select("div > article > div.box_in[id='search result']")
        return headers.mapNotNull { h ->
            val name = h?.selectFirst(" div > h2.title > a > b")?.text() ?: return@mapNotNull null
            val cUrl = fixUrlNull( h.selectFirst(" div > h2.title > a ")?.attr("href"))?:""

            newSearchResponse(
                name = name,
                url = cUrl,
            ) {
                posterHeaders = baseHeaders
                posterUrl = fixUrlNull(h.selectFirst("div > a.highslide > img")?.attr("src"))
            }
        }
    }

    override suspend fun load(url: String): LoadResponse? {
        val document =app.get(url, headers =baseHeaders).document
        val name =
            document.selectFirst(" h2 ")?.text()?.substringBefore(", page")?.substringBefore("#")
                ?: return null

        val data: ArrayList<ChapterData> = ArrayList()
        val chapters = document.select("div.splitnewsnavigation2.ignore-select > center > div > a")

        data.add(
            newChapterData(
                name = "page 1",
                url = url.substringBeforeLast("/") + "/page,1," + url.substringAfterLast("/"),
            )
        )

        for (c in 0..(chapters.size / 2)) {
            if (chapters[c].attr("href").contains("category").not()) {
                val cUrl = chapters[c].attr("href")
                val cName = "page " + chapters[c].text()
                data.add(newChapterData(name = cName, url = cUrl))
            }
        }

        data.sortWith { first, second ->
            if (first.name.substringAfter(" ") != second.name.substringAfter(" ")) {
                first.name.substringAfter(" ").toInt() - second.name.substringAfter(" ").toInt()
            } else {
                first.name.compareTo(second.name)
            }
        }

        return newStreamResponse(url = url, name = name, data = data.distinctBy { it.url }) {
            author =
                document.selectFirst("#dle-speedbar > div > div > ul > li:nth-child(3) > a > span")
                    ?.text()
            posterHeaders = baseHeaders
            posterUrl =
                fixUrlNull(
                    document.selectFirst("div.box_in > center > div > a > img")
                        ?.attr("src")
                )
        }

    }
}